"""Shared reference data for backend/scripts/bootstrap_alembic.py and
backend/scripts/check_migration_drift.py — see docs/database/MIGRATIONS.md.

KNOWN_LEGACY_DUPLICATE_INDEXES: real, harmless index-name duplication that
exists on every database this application has ever run against (see
alembic/versions/0001_legacy_baseline.py's own comment for the full
history: the OLD run_migrations() raw SQL created these BEFORE/ALONGSIDE
the declarative models' own `index=True` columns, and they were never
cleaned up). Not a schema bug, not drift — an intentional, narrow
allowlist so the drift check doesn't cry wolf on a database that's
actually fine. Every excluded name is listed explicitly here, never a
blanket "ignore unknown extras."

KNOWN_PRODUCTION_LEGACY_EXTRA_INDEXES: the SAME kind of harmless
duplication, one generation later — short-name indexes the OLD
interoperability-era `run_migrations()` raw SQL created (commit b6d8ae9,
"Add interoperability Phase 1: real FHIR R4 inbound connector") ALONGSIDE
the properly-named indexes SQLAlchemy's own declarative models (and later
0002_interop_phase1's autogenerated migration) already created on the same
columns. Kept as a SEPARATE, explicitly-named set from
KNOWN_LEGACY_DUPLICATE_INDEXES (which predates interoperability entirely)
so each allowlist's origin stays traceable — never merged into one vague
"ignore extra indexes" bucket. Recognized by
backend/scripts/bootstrap_alembic.py's known-production-variant
reconciliation path (see that module's "Production legacy variant
reconciliation" section) and, since a database that went through that
repair carries these permanently, also tolerated by
check_migration_drift.py's general gate — same treatment as
KNOWN_LEGACY_DUPLICATE_INDEXES already gets, just a separate, later-dated
allowlist.

  - ix_iic_connection_id / ix_iic_resolved — duplicate
    interop_identity_conflicts.connection_id / .resolved (canonical:
    ix_interop_identity_conflicts_connection_id / _resolved).
  - ix_epil_connection_id / _patient_id / _identifier_system /
    _identifier_value — duplicate interop_patient_identity_links columns
    (canonical: ix_interop_patient_identity_links_*).
  - ix_itm_connection_id / _source_code / _status — duplicate
    interop_terminology_mappings columns (canonical:
    ix_interop_terminology_mappings_*).
"""

KNOWN_LEGACY_DUPLICATE_INDEXES = frozenset(
    {
        "ix_eas_user",
        "ix_eas_patient",
        "ix_eas_public_id",
        "ix_eal_user",
        "ix_eal_patient",
        "ix_eal_session",
        "ix_eal_action",
        "ix_ec_patient",
    }
)

KNOWN_PRODUCTION_LEGACY_EXTRA_INDEXES = frozenset(
    {
        "ix_iic_connection_id",
        "ix_iic_resolved",
        "ix_epil_connection_id",
        "ix_epil_patient_id",
        "ix_epil_identifier_system",
        "ix_epil_identifier_value",
        "ix_itm_connection_id",
        "ix_itm_source_code",
        "ix_itm_status",
    }
)

# documents.original_layout_json: a Column(Text, nullable=True) added to
# app/models.py by commit 249b194 ("Add original layout payload and
# discharge reader fixes"), applied to production by the OLD
# run_migrations()/create_all() startup path at the time, then REMOVED
# from app/models.py by commit 6825cbb ("Rebuild discharge pipeline with
# OpenAI direct document reading") once the discharge pipeline stopped
# needing it — app/main.py still reads it defensively via
# `getattr(document, "original_layout_json", None)`, never as a declared
# ORM column. The column itself was never dropped from any real database
# (no migration ever declared that removal, deliberately — see
# docs/database/MIGRATIONS.md's "Backward compatibility" expand/contract
# policy: a real production database never gets code-only changes applied
# retroactively). Confirmed empty (0 non-null rows) on production as of
# 2026-09-17, but its contents are irrelevant here — this allowlist
# preserves the COLUMN, never inspects or depends on what's in it. A
# narrow, explicitly-named allowlist of exactly this one column — never a
# wildcard "ignore unknown extra columns" rule. Recognized by
# bootstrap_alembic.py's known-production-variant reconciliation path and,
# since a repaired database carries it permanently, also tolerated by
# check_migration_drift.py's general gate.
KNOWN_PRODUCTION_LEGACY_EXTRA_COLUMNS = frozenset(
    {
        ("documents", "original_layout_json"),
    }
)


def flatten_diff(diff: list) -> list[tuple]:
    """alembic.autogenerate.compare_metadata groups "modify column"
    operations (type/nullable/server_default/comment changes) into a
    nested list of one-or-more tuples per column, unlike every other diff
    kind (add_table, add_column, add_index, add_fk, remove_index, ...)
    which are flat tuples directly in the top-level list. Normalize to a
    flat list of plain tuples so callers can treat every entry uniformly."""
    flat: list[tuple] = []
    for item in diff:
        if isinstance(item, list):
            flat.extend(item)
        else:
            flat.append(item)
    return flat


def entry_label(entry: tuple) -> str:
    """Human-readable label for one flattened compare_metadata diff entry —
    handles every kind's differing tuple shape (add_column's table/column
    name sit at different positions than add_table/add_index/add_fk/
    remove_index/modify_*)."""
    kind = entry[0]
    if kind == "add_column":
        return f"{kind}: {entry[2]}.{entry[3].name}"
    if kind.startswith("modify_"):
        table_name, column_name = entry[2], entry[3]
        return f"{kind}: {table_name}.{column_name}"
    target = entry[1] if len(entry) > 1 else None
    name = getattr(target, "name", None) or (entry[2] if len(entry) > 2 else str(target))
    return f"{kind}: {name}"
