"""legacy baseline (pre-interop)

This is the FROZEN, IMMUTABLE schema of `main` at commit 397125a — the
last commit before the interoperability work (BRAGI_INTEROP_PLAN.md). It
was generated once via `alembic revision --autogenerate` with
target_metadata temporarily pointed at that commit's `app/models.py`
(via a git worktree), diffed against a genuinely empty database — see
docs/database/MIGRATIONS.md for exactly how, and how to regenerate this
process if it's ever needed again. The generated operations were verified
to reproduce, table-for-table and column-for-column, the schema this
repo's OWN pre-interop `run_migrations()`/`Base.metadata.create_all()`
bootstrap produces on a fresh database (see that doc's "Verifying the
baseline" section for the exact diff check).

DO NOT EDIT THIS FILE after it has been applied anywhere. If the legacy
schema was ever wrong, fix it in a NEW migration, never by rewriting
history a real database may have already applied.

For an EXISTING production database (which got its schema from the old
`run_migrations()` code, not from this file), this revision is never
literally run — it is `alembic stamp 0001` (an operator action — see
docs/database/MIGRATIONS.md / backend/scripts/bootstrap_alembic.py) after
verifying the live schema actually matches what this file would have
produced. Only a genuinely NEW/empty database runs this file's upgrade()
for real.

Revision ID: 77df8fa2b964
Revises:
Create Date: 2026-09-11 20:46:31.839996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77df8fa2b964'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('doctor_type', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('cnp', sa.String(), nullable=True),
    sa.Column('patient_identifier', sa.String(), nullable=True),
    sa.Column('emergency_search_enabled', sa.Integer(), nullable=False),
    sa.Column('emergency_search_updated_at', sa.String(), nullable=True),
    sa.Column('emergency_search_consent_text_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_cnp'), 'patients', ['cnp'], unique=False)
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_identifier'), 'patients', ['patient_identifier'], unique=False)
    op.create_index(op.f('ix_patients_public_id'), 'patients', ['public_id'], unique=True)
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    # ondelete='SET NULL' — not declared on the Column itself in
    # app/models.py (a pre-existing gap predating this baseline), but the
    # OLD run_migrations() idempotently upgraded every real database's
    # actual constraint to this exact delete rule (see its own DO-block
    # comments) — a faithful baseline has to match reality, not the
    # (incomplete) Python declaration. See docs/database/MIGRATIONS.md's
    # "Verifying the baseline" for how this was found.
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_admin_user_id'), 'admin_action_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_doctor_user_id'), 'admin_action_logs', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_id'), 'admin_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_patient_id'), 'admin_action_logs', ['patient_id'], unique=False)
    op.create_table('care_partner_patient_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_partner_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['care_partner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_partner_patient_links_care_partner_user_id'), 'care_partner_patient_links', ['care_partner_user_id'], unique=False)
    op.create_index(op.f('ix_care_partner_patient_links_id'), 'care_partner_patient_links', ['id'], unique=False)
    op.create_index(op.f('ix_care_partner_patient_links_patient_id'), 'care_partner_patient_links', ['patient_id'], unique=False)
    op.create_table('doctor_patient_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_access_doctor_user_id'), 'doctor_patient_access', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_id'), 'doctor_patient_access', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_is_active'), 'doctor_patient_access', ['is_active'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_patient_id'), 'doctor_patient_access', ['patient_id'], unique=False)
    op.create_table('doctor_patient_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.String(), nullable=False),
    sa.Column('responded_at', sa.String(), nullable=True),
    sa.Column('responded_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_access_requests_doctor_user_id'), 'doctor_patient_access_requests', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_requests_id'), 'doctor_patient_access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_requests_patient_id'), 'doctor_patient_access_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_requests_status'), 'doctor_patient_access_requests', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('saved_to', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('cnp', sa.String(), nullable=True),
    sa.Column('patient_identifier', sa.String(), nullable=True),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('sample_type', sa.String(), nullable=True),
    sa.Column('referring_doctor', sa.String(), nullable=True),
    sa.Column('report_name', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('source_language', sa.String(), nullable=True),
    sa.Column('test_date', sa.String(), nullable=True),
    sa.Column('collected_on', sa.String(), nullable=True),
    sa.Column('reported_on', sa.String(), nullable=True),
    sa.Column('registered_on', sa.String(), nullable=True),
    sa.Column('generated_on', sa.String(), nullable=True),
    sa.Column('note_body', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('classification_status', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_source', sa.String(), nullable=True),
    sa.Column('file_sha256', sa.String(), nullable=True),
    sa.Column('identity_status', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('intended_patient_id', sa.Integer(), nullable=True),
    sa.Column('structured_sections', sa.Text(), nullable=True),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('parent_document_id', sa.Integer(), nullable=True),
    sa.Column('page_range_start', sa.Integer(), nullable=True),
    sa.Column('page_range_end', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.String(), nullable=True),
    sa.Column('last_edited_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['intended_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_sha256'), 'documents', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_intended_patient_id'), 'documents', ['intended_patient_id'], unique=False)
    op.create_index(op.f('ix_documents_parent_document_id'), 'documents', ['parent_document_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_documents_public_id'), 'documents', ['public_id'], unique=True)
    op.create_index(op.f('ix_documents_review_status'), 'documents', ['review_status'], unique=False)
    op.create_index(op.f('ix_documents_section'), 'documents', ['section'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_table('emergency_access_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('emergency_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['emergency_user_id'], ['users.id'], ),
    # ondelete='SET NULL' — see admin_action_logs' identical comment above.
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_access_sessions_emergency_user_id'), 'emergency_access_sessions', ['emergency_user_id'], unique=False)
    op.create_index(op.f('ix_emergency_access_sessions_id'), 'emergency_access_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_access_sessions_patient_id'), 'emergency_access_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_access_sessions_public_id'), 'emergency_access_sessions', ['public_id'], unique=True)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_patient_id'), 'emergency_contacts', ['patient_id'], unique=False)
    op.create_table('patient_care_partner_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_care_partner_codes_code'), 'patient_care_partner_codes', ['code'], unique=True)
    op.create_index(op.f('ix_patient_care_partner_codes_id'), 'patient_care_partner_codes', ['id'], unique=False)
    op.create_index(op.f('ix_patient_care_partner_codes_patient_id'), 'patient_care_partner_codes', ['patient_id'], unique=True)
    op.create_table('patient_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('admitted_at', sa.String(), nullable=False),
    sa.Column('discharged_at', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discharged_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discharged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_events_doctor_user_id'), 'patient_events', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_patient_events_id'), 'patient_events', ['id'], unique=False)
    op.create_index(op.f('ix_patient_events_patient_id'), 'patient_events', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_events_status'), 'patient_events', ['status'], unique=False)
    op.create_table('patient_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose_strength', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('route_form', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('stop_date', sa.String(), nullable=True),
    sa.Column('prescriber', sa.String(), nullable=True),
    sa.Column('extra_info', sa.Text(), nullable=True),
    sa.Column('is_uncertain', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('official_match_status', sa.String(), nullable=True),
    sa.Column('official_source_name', sa.String(), nullable=True),
    sa.Column('official_source_url', sa.String(), nullable=True),
    sa.Column('rxnorm_rxcui', sa.String(), nullable=True),
    sa.Column('dailymed_setid', sa.String(), nullable=True),
    sa.Column('official_info_json', sa.Text(), nullable=True),
    sa.Column('official_retrieved_at', sa.String(), nullable=True),
    sa.Column('official_label_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medications_id'), 'patient_medications', ['id'], unique=False)
    op.create_index(op.f('ix_patient_medications_name'), 'patient_medications', ['name'], unique=False)
    op.create_index(op.f('ix_patient_medications_patient_id'), 'patient_medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_medications_status'), 'patient_medications', ['status'], unique=False)
    op.create_table('ask_bragi_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('owner_role', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('archived_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ask_bragi_conversations_document_id'), 'ask_bragi_conversations', ['document_id'], unique=False)
    op.create_index(op.f('ix_ask_bragi_conversations_id'), 'ask_bragi_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_ask_bragi_conversations_owner_user_id'), 'ask_bragi_conversations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_ask_bragi_conversations_patient_id'), 'ask_bragi_conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ask_bragi_conversations_public_id'), 'ask_bragi_conversations', ['public_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('doctor_document_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_document_reviews_doctor_user_id'), 'doctor_document_reviews', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_doctor_document_reviews_document_id'), 'doctor_document_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_doctor_document_reviews_id'), 'doctor_document_reviews', ['id'], unique=False)
    op.create_table('emergency_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    # ondelete='SET NULL' on all three — see admin_action_logs' identical
    # comment above (same real, run_migrations()-applied delete rule).
    sa.ForeignKeyConstraint(['emergency_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['emergency_access_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_audit_logs_action'), 'emergency_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_emergency_audit_logs_emergency_user_id'), 'emergency_audit_logs', ['emergency_user_id'], unique=False)
    op.create_index(op.f('ix_emergency_audit_logs_id'), 'emergency_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_audit_logs_patient_id'), 'emergency_audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_emergency_audit_logs_session_id'), 'emergency_audit_logs', ['session_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('raw_test_name', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_section', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('reference_range', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('observation_datetime', sa.String(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('specimen', sa.String(), nullable=True),
    sa.Column('accession_id', sa.String(), nullable=True),
    sa.Column('verification_state', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('normalization_confidence', sa.Float(), nullable=True),
    sa.Column('normalization_method', sa.String(), nullable=True),
    sa.Column('duplicate_of_lab_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_lab_result_id'], ['lab_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_canonical_name'), 'lab_results', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_lab_results_category'), 'lab_results', ['category'], unique=False)
    op.create_index(op.f('ix_lab_results_document_id'), 'lab_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_index(op.f('ix_lab_results_observation_datetime'), 'lab_results', ['observation_datetime'], unique=False)
    op.create_table('note_document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_document_id', sa.Integer(), nullable=False),
    sa.Column('linked_document_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['note_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_document_links_id'), 'note_document_links', ['id'], unique=False)
    op.create_index(op.f('ix_note_document_links_linked_document_id'), 'note_document_links', ['linked_document_id'], unique=False)
    op.create_index(op.f('ix_note_document_links_note_document_id'), 'note_document_links', ['note_document_id'], unique=False)
    op.create_table('shared_structured_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('care_partner_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_patient_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['care_partner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_by_patient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_structured_pages_care_partner_user_id'), 'shared_structured_pages', ['care_partner_user_id'], unique=False)
    op.create_index(op.f('ix_shared_structured_pages_document_id'), 'shared_structured_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_shared_structured_pages_id'), 'shared_structured_pages', ['id'], unique=False)
    op.create_index(op.f('ix_shared_structured_pages_shared_by_patient_user_id'), 'shared_structured_pages', ['shared_by_patient_user_id'], unique=False)
    op.create_table('upload_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('saved_to', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('classification_status', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_source', sa.String(), nullable=True),
    sa.Column('file_sha256', sa.String(), nullable=True),
    sa.Column('identity_status', sa.String(), nullable=True),
    sa.Column('identity_override', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_jobs_document_id'), 'upload_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_document_type'), 'upload_jobs', ['document_type'], unique=False)
    op.create_index(op.f('ix_upload_jobs_file_sha256'), 'upload_jobs', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_upload_jobs_id'), 'upload_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_patient_id'), 'upload_jobs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_section'), 'upload_jobs', ['section'], unique=False)
    op.create_index(op.f('ix_upload_jobs_status'), 'upload_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_upload_jobs_user_id'), 'upload_jobs', ['user_id'], unique=False)
    op.create_table('ask_bragi_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('chart_json', sa.Text(), nullable=True),
    sa.Column('follow_ups_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scope_used', sa.String(), nullable=True),
    sa.Column('tool_categories_json', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tool_schema_version', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ask_bragi_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ask_bragi_messages_conversation_id'), 'ask_bragi_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ask_bragi_messages_id'), 'ask_bragi_messages', ['id'], unique=False)
    op.create_table('source_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('lab_result_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_width', sa.Float(), nullable=True),
    sa.Column('bbox_height', sa.Float(), nullable=True),
    sa.Column('row_bbox_x', sa.Float(), nullable=True),
    sa.Column('row_bbox_y', sa.Float(), nullable=True),
    sa.Column('row_bbox_width', sa.Float(), nullable=True),
    sa.Column('row_bbox_height', sa.Float(), nullable=True),
    sa.Column('source_block_id', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['lab_result_id'], ['lab_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_evidence_document_id'), 'source_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_source_evidence_id'), 'source_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_source_evidence_lab_result_id'), 'source_evidence', ['lab_result_id'], unique=False)
    # ### end Alembic commands (autogenerated from app.models declarations) ###

    # --- Hand-added: real historical duplicate indexes ------------------
    # Not part of any declarative model — these were created by the OLD
    # run_migrations() raw SQL (see e.g. main.py's historical
    # `CREATE INDEX IF NOT EXISTS ix_eas_user ...` block) ALONGSIDE the
    # properly-named indexes SQLAlchemy's create_all() already created
    # from the declared models (e.g. `ix_emergency_access_sessions_
    # emergency_user_id`), and were never cleaned up. Functionally
    # redundant (same columns, same purpose) but REAL and PRESENT on every
    # database that has run this application's startup code — a faithful
    # "exact schema of main" baseline has to include them, or
    # bootstrap_alembic.py's drift check would flag every real database as
    # unexpectedly drifted. Confirmed by diffing a real bootstrap of main
    # (397125a) against this file's own generated schema before adding
    # these — see docs/database/MIGRATIONS.md's "Verifying the baseline".
    op.create_index('ix_eas_user', 'emergency_access_sessions', ['emergency_user_id'], unique=False)
    op.create_index('ix_eas_patient', 'emergency_access_sessions', ['patient_id'], unique=False)
    op.create_index(
        'ix_eas_public_id',
        'emergency_access_sessions',
        ['public_id'],
        unique=True,
        postgresql_where=sa.text('public_id IS NOT NULL'),
    )
    op.create_index('ix_eal_user', 'emergency_audit_logs', ['emergency_user_id'], unique=False)
    op.create_index('ix_eal_patient', 'emergency_audit_logs', ['patient_id'], unique=False)
    op.create_index('ix_eal_session', 'emergency_audit_logs', ['session_id'], unique=False)
    op.create_index('ix_eal_action', 'emergency_audit_logs', ['action'], unique=False)
    op.create_index('ix_ec_patient', 'emergency_contacts', ['patient_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    DESTRUCTIVE: this drops every table this application has ever had,
    including `users`, `patients`, `documents`, `lab_results` — every
    real patient/clinical record. This function exists so the migration
    is technically reversible on a DISPOSABLE database (see the migration
    upgrade/downgrade tests in tests/test_migrations.py), never as a real
    production rollback tool.

    Per BRAGI_INTEROP_PLAN.md / docs/database/MIGRATIONS.md's rollback
    policy: production rollback means an application-code rollback plus a
    backward-compatible schema, or a forward-fix migration — NEVER
    downgrading past this revision on a database with real data. This
    guard fails closed unless the operator explicitly opts in.
    """
    import os

    if os.getenv("ALEMBIC_ALLOW_DESTRUCTIVE_DOWNGRADE") != "yes-i-am-sure":
        raise RuntimeError(
            "Refusing to downgrade past the legacy baseline — this would DROP EVERY TABLE "
            "in the database, including users/patients/documents/lab_results. If you are "
            "certain this is a disposable/test database, set "
            "ALEMBIC_ALLOW_DESTRUCTIVE_DOWNGRADE=yes-i-am-sure and re-run. This is never the "
            "right move against a database with real data — see docs/database/MIGRATIONS.md."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_evidence_lab_result_id'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_id'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_document_id'), table_name='source_evidence')
    op.drop_table('source_evidence')
    op.drop_index(op.f('ix_ask_bragi_messages_id'), table_name='ask_bragi_messages')
    op.drop_index(op.f('ix_ask_bragi_messages_conversation_id'), table_name='ask_bragi_messages')
    op.drop_table('ask_bragi_messages')
    op.drop_index(op.f('ix_upload_jobs_user_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_status'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_section'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_patient_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_file_sha256'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_document_type'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_document_id'), table_name='upload_jobs')
    op.drop_table('upload_jobs')
    op.drop_index(op.f('ix_shared_structured_pages_shared_by_patient_user_id'), table_name='shared_structured_pages')
    op.drop_index(op.f('ix_shared_structured_pages_id'), table_name='shared_structured_pages')
    op.drop_index(op.f('ix_shared_structured_pages_document_id'), table_name='shared_structured_pages')
    op.drop_index(op.f('ix_shared_structured_pages_care_partner_user_id'), table_name='shared_structured_pages')
    op.drop_table('shared_structured_pages')
    op.drop_index(op.f('ix_note_document_links_note_document_id'), table_name='note_document_links')
    op.drop_index(op.f('ix_note_document_links_linked_document_id'), table_name='note_document_links')
    op.drop_index(op.f('ix_note_document_links_id'), table_name='note_document_links')
    op.drop_table('note_document_links')
    op.drop_index(op.f('ix_lab_results_observation_datetime'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_document_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_category'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_canonical_name'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_emergency_audit_logs_session_id'), table_name='emergency_audit_logs')
    op.drop_index(op.f('ix_emergency_audit_logs_patient_id'), table_name='emergency_audit_logs')
    op.drop_index(op.f('ix_emergency_audit_logs_id'), table_name='emergency_audit_logs')
    op.drop_index(op.f('ix_emergency_audit_logs_emergency_user_id'), table_name='emergency_audit_logs')
    op.drop_index(op.f('ix_emergency_audit_logs_action'), table_name='emergency_audit_logs')
    op.drop_table('emergency_audit_logs')
    op.drop_index(op.f('ix_doctor_document_reviews_id'), table_name='doctor_document_reviews')
    op.drop_index(op.f('ix_doctor_document_reviews_document_id'), table_name='doctor_document_reviews')
    op.drop_index(op.f('ix_doctor_document_reviews_doctor_user_id'), table_name='doctor_document_reviews')
    op.drop_table('doctor_document_reviews')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ask_bragi_conversations_public_id'), table_name='ask_bragi_conversations')
    op.drop_index(op.f('ix_ask_bragi_conversations_patient_id'), table_name='ask_bragi_conversations')
    op.drop_index(op.f('ix_ask_bragi_conversations_owner_user_id'), table_name='ask_bragi_conversations')
    op.drop_index(op.f('ix_ask_bragi_conversations_id'), table_name='ask_bragi_conversations')
    op.drop_index(op.f('ix_ask_bragi_conversations_document_id'), table_name='ask_bragi_conversations')
    op.drop_table('ask_bragi_conversations')
    op.drop_index(op.f('ix_patient_medications_status'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_patient_id'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_name'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    op.drop_index(op.f('ix_patient_events_status'), table_name='patient_events')
    op.drop_index(op.f('ix_patient_events_patient_id'), table_name='patient_events')
    op.drop_index(op.f('ix_patient_events_id'), table_name='patient_events')
    op.drop_index(op.f('ix_patient_events_doctor_user_id'), table_name='patient_events')
    op.drop_table('patient_events')
    op.drop_index(op.f('ix_patient_care_partner_codes_patient_id'), table_name='patient_care_partner_codes')
    op.drop_index(op.f('ix_patient_care_partner_codes_id'), table_name='patient_care_partner_codes')
    op.drop_index(op.f('ix_patient_care_partner_codes_code'), table_name='patient_care_partner_codes')
    op.drop_table('patient_care_partner_codes')
    op.drop_index(op.f('ix_emergency_contacts_patient_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_emergency_access_sessions_public_id'), table_name='emergency_access_sessions')
    op.drop_index(op.f('ix_emergency_access_sessions_patient_id'), table_name='emergency_access_sessions')
    op.drop_index(op.f('ix_emergency_access_sessions_id'), table_name='emergency_access_sessions')
    op.drop_index(op.f('ix_emergency_access_sessions_emergency_user_id'), table_name='emergency_access_sessions')
    op.drop_table('emergency_access_sessions')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_section'), table_name='documents')
    op.drop_index(op.f('ix_documents_review_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_public_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_parent_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_intended_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_doctor_patient_access_requests_status'), table_name='doctor_patient_access_requests')
    op.drop_index(op.f('ix_doctor_patient_access_requests_patient_id'), table_name='doctor_patient_access_requests')
    op.drop_index(op.f('ix_doctor_patient_access_requests_id'), table_name='doctor_patient_access_requests')
    op.drop_index(op.f('ix_doctor_patient_access_requests_doctor_user_id'), table_name='doctor_patient_access_requests')
    op.drop_table('doctor_patient_access_requests')
    op.drop_index(op.f('ix_doctor_patient_access_patient_id'), table_name='doctor_patient_access')
    op.drop_index(op.f('ix_doctor_patient_access_is_active'), table_name='doctor_patient_access')
    op.drop_index(op.f('ix_doctor_patient_access_id'), table_name='doctor_patient_access')
    op.drop_index(op.f('ix_doctor_patient_access_doctor_user_id'), table_name='doctor_patient_access')
    op.drop_table('doctor_patient_access')
    op.drop_index(op.f('ix_care_partner_patient_links_patient_id'), table_name='care_partner_patient_links')
    op.drop_index(op.f('ix_care_partner_patient_links_id'), table_name='care_partner_patient_links')
    op.drop_index(op.f('ix_care_partner_patient_links_care_partner_user_id'), table_name='care_partner_patient_links')
    op.drop_table('care_partner_patient_links')
    op.drop_index(op.f('ix_admin_action_logs_patient_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_doctor_user_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_admin_user_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    op.drop_index(op.f('ix_patients_public_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_identifier'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_cnp'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
