"""interop phase1

Adds interoperability Phase 1 (BRAGI_INTEROP_PLAN.md): 6 new tables
(InteropSecret, InteropConnection, InteropSyncRun,
ExternalPatientIdentityLink, InteropIdentityConflict,
InteropTerminologyMapping) plus 2 additive nullable columns
(documents.source_connection_id, lab_results.source_connection_id/
external_observation_id). Purely additive — no existing table, column,
or constraint from 0001 is touched. Generated the same way as 0001 (see
that revision's docstring and docs/database/MIGRATIONS.md), then verified
to exactly match the schema this branch's own application bootstrap
produces on a fresh database.

For an EXISTING database that already has this schema (created by the
OLD `run_migrations()` startup code before this Alembic conversion), this
is `alembic stamp 0002` after verification — see
backend/scripts/bootstrap_alembic.py — not a real re-run of upgrade().

Revision ID: 4cf06d926267
Revises: 77df8fa2b964
Create Date: 2026-09-11 20:47:01.509082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf06d926267'
down_revision: Union[str, Sequence[str], None] = '77df8fa2b964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interop_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('rotated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_secrets_id'), 'interop_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_interop_secrets_ref'), 'interop_secrets', ['ref'], unique=True)
    op.create_table('interop_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connector_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('fhir_version', sa.String(), nullable=True),
    sa.Column('allow_private_network', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=False),
    sa.Column('auth_config_json', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.String(), nullable=True),
    sa.Column('patient_identity_json', sa.Text(), nullable=True),
    sa.Column('capabilities_json', sa.Text(), nullable=True),
    sa.Column('capabilities_discovered_at', sa.String(), nullable=True),
    sa.Column('terminology_overrides_json', sa.Text(), nullable=True),
    sa.Column('sync_config_json', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['secret_ref'], ['interop_secrets.ref'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_connections_connector_type'), 'interop_connections', ['connector_type'], unique=False)
    op.create_index(op.f('ix_interop_connections_id'), 'interop_connections', ['id'], unique=False)
    op.create_index(op.f('ix_interop_connections_public_id'), 'interop_connections', ['public_id'], unique=True)
    op.create_index(op.f('ix_interop_connections_status'), 'interop_connections', ['status'], unique=False)
    op.create_table('interop_patient_identity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('identifier_system', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('verified_at', sa.String(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['interop_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_patient_identity_links_connection_id'), 'interop_patient_identity_links', ['connection_id'], unique=False)
    op.create_index(op.f('ix_interop_patient_identity_links_id'), 'interop_patient_identity_links', ['id'], unique=False)
    op.create_index(op.f('ix_interop_patient_identity_links_identifier_system'), 'interop_patient_identity_links', ['identifier_system'], unique=False)
    op.create_index(op.f('ix_interop_patient_identity_links_identifier_value'), 'interop_patient_identity_links', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_interop_patient_identity_links_patient_id'), 'interop_patient_identity_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_interop_patient_identity_links_status'), 'interop_patient_identity_links', ['status'], unique=False)
    op.create_table('interop_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('started_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['interop_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_sync_runs_connection_id'), 'interop_sync_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_interop_sync_runs_id'), 'interop_sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_interop_sync_runs_run_type'), 'interop_sync_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_interop_sync_runs_status'), 'interop_sync_runs', ['status'], unique=False)
    op.create_table('interop_terminology_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('source_display', sa.String(), nullable=True),
    sa.Column('target_canonical_name', sa.String(), nullable=True),
    sa.Column('target_display_name', sa.String(), nullable=True),
    sa.Column('target_category', sa.String(), nullable=True),
    sa.Column('target_unit', sa.String(), nullable=True),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('frequency_seen', sa.Integer(), nullable=False),
    sa.Column('example_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['interop_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_terminology_mappings_connection_id'), 'interop_terminology_mappings', ['connection_id'], unique=False)
    op.create_index(op.f('ix_interop_terminology_mappings_id'), 'interop_terminology_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_interop_terminology_mappings_source_code'), 'interop_terminology_mappings', ['source_code'], unique=False)
    op.create_index(op.f('ix_interop_terminology_mappings_status'), 'interop_terminology_mappings', ['status'], unique=False)
    op.create_table('interop_identity_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('identifier_system', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('existing_link_id', sa.Integer(), nullable=True),
    sa.Column('attempted_patient_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempted_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['interop_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['existing_link_id'], ['interop_patient_identity_links.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interop_identity_conflicts_connection_id'), 'interop_identity_conflicts', ['connection_id'], unique=False)
    op.create_index(op.f('ix_interop_identity_conflicts_id'), 'interop_identity_conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_interop_identity_conflicts_resolved'), 'interop_identity_conflicts', ['resolved'], unique=False)
    op.add_column('documents', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_source_connection_id'), 'documents', ['source_connection_id'], unique=False)
    # Named explicitly (Postgres's own default-naming convention,
    # `{table}_{column}_fkey`) rather than left as `None` — the
    # autogenerated downgrade() needs a real name to drop, and `None`
    # would fail at downgrade time despite upgrading fine (caught by
    # this migration's own upgrade/downgrade round-trip test).
    op.create_foreign_key('documents_source_connection_id_fkey', 'documents', 'interop_connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    op.add_column('lab_results', sa.Column('source_connection_id', sa.Integer(), nullable=True))
    op.add_column('lab_results', sa.Column('external_observation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_lab_results_external_observation_id'), 'lab_results', ['external_observation_id'], unique=False)
    op.create_index(op.f('ix_lab_results_source_connection_id'), 'lab_results', ['source_connection_id'], unique=False)
    op.create_foreign_key('lab_results_source_connection_id_fkey', 'lab_results', 'interop_connections', ['source_connection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Safe on a database with real data — this only removes what Phase 1
    itself added (6 new tables, 2 additive columns). No pre-existing
    table/column/row is touched. One caveat: dropping
    lab_results.source_connection_id/external_observation_id loses the
    link back to whichever InteropConnection synced a given LabResult row
    — the row itself is NOT deleted, only its interop provenance
    tracking. Never run this against a database with a real, in-use
    interop connection without accepting that loss.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lab_results_source_connection_id_fkey', 'lab_results', type_='foreignkey')
    op.drop_index(op.f('ix_lab_results_source_connection_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_external_observation_id'), table_name='lab_results')
    op.drop_column('lab_results', 'external_observation_id')
    op.drop_column('lab_results', 'source_connection_id')
    op.drop_constraint('documents_source_connection_id_fkey', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_source_connection_id'), table_name='documents')
    op.drop_column('documents', 'source_connection_id')
    op.drop_index(op.f('ix_interop_identity_conflicts_resolved'), table_name='interop_identity_conflicts')
    op.drop_index(op.f('ix_interop_identity_conflicts_id'), table_name='interop_identity_conflicts')
    op.drop_index(op.f('ix_interop_identity_conflicts_connection_id'), table_name='interop_identity_conflicts')
    op.drop_table('interop_identity_conflicts')
    op.drop_index(op.f('ix_interop_terminology_mappings_status'), table_name='interop_terminology_mappings')
    op.drop_index(op.f('ix_interop_terminology_mappings_source_code'), table_name='interop_terminology_mappings')
    op.drop_index(op.f('ix_interop_terminology_mappings_id'), table_name='interop_terminology_mappings')
    op.drop_index(op.f('ix_interop_terminology_mappings_connection_id'), table_name='interop_terminology_mappings')
    op.drop_table('interop_terminology_mappings')
    op.drop_index(op.f('ix_interop_sync_runs_status'), table_name='interop_sync_runs')
    op.drop_index(op.f('ix_interop_sync_runs_run_type'), table_name='interop_sync_runs')
    op.drop_index(op.f('ix_interop_sync_runs_id'), table_name='interop_sync_runs')
    op.drop_index(op.f('ix_interop_sync_runs_connection_id'), table_name='interop_sync_runs')
    op.drop_table('interop_sync_runs')
    op.drop_index(op.f('ix_interop_patient_identity_links_status'), table_name='interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_patient_identity_links_patient_id'), table_name='interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_patient_identity_links_identifier_value'), table_name='interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_patient_identity_links_identifier_system'), table_name='interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_patient_identity_links_id'), table_name='interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_patient_identity_links_connection_id'), table_name='interop_patient_identity_links')
    op.drop_table('interop_patient_identity_links')
    op.drop_index(op.f('ix_interop_connections_status'), table_name='interop_connections')
    op.drop_index(op.f('ix_interop_connections_public_id'), table_name='interop_connections')
    op.drop_index(op.f('ix_interop_connections_id'), table_name='interop_connections')
    op.drop_index(op.f('ix_interop_connections_connector_type'), table_name='interop_connections')
    op.drop_table('interop_connections')
    op.drop_index(op.f('ix_interop_secrets_ref'), table_name='interop_secrets')
    op.drop_index(op.f('ix_interop_secrets_id'), table_name='interop_secrets')
    op.drop_table('interop_secrets')
    # ### end Alembic commands ###
