"""phase3 hardening

Revision ID: 2398fbce8a2c
Revises: 4cf06d926267
Create Date: 2026-09-11 21:52:08.438674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2398fbce8a2c'
down_revision: Union[str, Sequence[str], None] = '4cf06d926267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerate also proposed dropping 8 harmless historical duplicate
    indexes (ix_eas_*/ix_eal_*/ix_ec_patient — see
    _alembic_baseline_fingerprint.py and 0001_legacy_baseline.py's own
    comments) purely because app/models.py doesn't declare them as
    SQLAlchemy Index() objects. Deliberately removed from this migration —
    unrelated to Phase 3, and dropping them is a separate, deliberate
    cleanup decision for later, not a side effect of adding hardening
    columns.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interop_connections', sa.Column('capability_fingerprint', sa.String(), nullable=True))
    # server_default='0' — required: this is a NOT NULL column added to a
    # table that may already have rows (any Phase 1 connection created
    # before this migration runs). Without it, the ALTER TABLE fails on a
    # non-empty table. Matches the model's Python-level default=0.
    op.add_column('interop_connections', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interop_connections', sa.Column('last_failure_at', sa.String(), nullable=True))
    op.add_column('interop_connections', sa.Column('last_failure_reason', sa.String(), nullable=True))
    op.add_column('interop_connections', sa.Column('sync_cursor_json', sa.Text(), nullable=True))
    op.add_column('interop_connections', sa.Column('disabled_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interop_connections', 'disabled_at')
    op.drop_column('interop_connections', 'sync_cursor_json')
    op.drop_column('interop_connections', 'last_failure_reason')
    op.drop_column('interop_connections', 'last_failure_at')
    op.drop_column('interop_connections', 'consecutive_failures')
    op.drop_column('interop_connections', 'capability_fingerprint')
    # ### end Alembic commands ###
