import type { AnalyteEntry } from './types';

export const ANALYTE_CATALOG: AnalyteEntry[] = [

  // =========================================================
  // HEMATOLOGIE / CBC
  // =========================================================
  {
    id: 'WBC',
    loinc: '6690-2',
    canonicalName: { en: 'White Blood Cell Count', ro: 'Leucocite' },
    aliases: ['wbc', 'leu', 'leucocite', 'leucocytes', 'white blood cells', 'numar leucocite', 'globule albe'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL', alternatives: ['10^3/uL', 'G/L', 'K/uL'] },
    referenceRanges: [{ sex: 'any', low: 4.5, high: 11.0, unit: '×10³/μL' }],
  },
  {
    id: 'RBC',
    loinc: '789-8',
    canonicalName: { en: 'Red Blood Cell Count', ro: 'Eritrocite' },
    aliases: ['rbc', 'eritrocite', 'erythrocytes', 'red blood cells', 'hematii', 'globule rosii'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10⁶/μL', alternatives: ['10^6/uL', 'T/L', 'M/uL'] },
    referenceRanges: [
      { sex: 'M', low: 4.5, high: 5.9, unit: '×10⁶/μL' },
      { sex: 'F', low: 4.1, high: 5.1, unit: '×10⁶/μL' },
    ],
  },
  {
    id: 'HGB',
    loinc: '718-7',
    canonicalName: { en: 'Hemoglobin', ro: 'Hemoglobina' },
    aliases: ['hgb', 'hb', 'hemoglobina', 'hemoglobin', 'haemoglobin'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'g/dL', alternatives: ['g/L'] },
    referenceRanges: [
      { sex: 'M', low: 13.5, high: 17.5, unit: 'g/dL' },
      { sex: 'F', low: 12.0, high: 16.0, unit: 'g/dL' },
    ],
    criticalBands: [{ low: 7.0, unit: 'g/dL' }],
    trendIsClinicallyPrimary: false,
  },
  {
    id: 'HCT',
    loinc: '4544-3',
    canonicalName: { en: 'Hematocrit', ro: 'Hematocrit' },
    aliases: ['hct', 'ht', 'hematocrit', 'haematocrit'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [
      { sex: 'M', low: 41, high: 53, unit: '%' },
      { sex: 'F', low: 36, high: 46, unit: '%' },
    ],
  },
  {
    id: 'MCV',
    loinc: '787-2',
    canonicalName: { en: 'Mean Corpuscular Volume', ro: 'Volum Eritrocitar Mediu' },
    aliases: ['mcv', 'vem', 'volum eritrocitar mediu', 'mean corpuscular volume', 'mean cell volume'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'fL' },
    referenceRanges: [{ sex: 'any', low: 80, high: 100, unit: 'fL' }],
  },
  {
    id: 'MCH',
    loinc: '785-6',
    canonicalName: { en: 'Mean Corpuscular Hemoglobin', ro: 'Hemoglobina Eritrocitara Medie' },
    aliases: ['mch', 'hem', 'hemoglobina eritrocitara medie', 'mean corpuscular hemoglobin'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'pg' },
    referenceRanges: [{ sex: 'any', low: 27, high: 33, unit: 'pg' }],
  },
  {
    id: 'MCHC',
    loinc: '786-4',
    canonicalName: { en: 'Mean Corpuscular Hemoglobin Concentration', ro: 'Concentratia Medie de Hemoglobina' },
    aliases: ['mchc', 'chcm', 'concentratia medie de hemoglobina', 'mean corpuscular hemoglobin concentration'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'g/dL', alternatives: ['g/L'] },
    referenceRanges: [{ sex: 'any', low: 32, high: 36, unit: 'g/dL' }],
  },
  {
    id: 'RDW_CV',
    loinc: '788-0',
    canonicalName: { en: 'Red Cell Distribution Width - CV', ro: 'Distributia Eritrocitara - CV' },
    aliases: ['rdw-cv', 'rdw cv', 'red cell distribution width cv', 'largimea distributiei eritrocitare cv'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 11.5, high: 14.5, unit: '%' }],
  },
  {
    id: 'RDW_SD',
    loinc: '21232-4',
    canonicalName: { en: 'Red Cell Distribution Width - SD', ro: 'Distributia Eritrocitara - SD' },
    aliases: ['rdw-sd', 'rdw sd', 'red cell distribution width sd', 'largimea distributiei eritrocitare sd'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'fL' },
    referenceRanges: [{ sex: 'any', low: 37, high: 54, unit: 'fL' }],
  },
  {
    id: 'PLT',
    loinc: '777-3',
    canonicalName: { en: 'Platelet Count', ro: 'Trombocite' },
    aliases: ['plt', 'plachete', 'trombocite', 'platelets', 'platelet count', 'numar trombocite'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL', alternatives: ['10^3/uL', 'G/L', 'K/uL'] },
    referenceRanges: [{ sex: 'any', low: 150, high: 400, unit: '×10³/μL' }],
    criticalBands: [{ low: 20, unit: '×10³/μL' }],
  },
  {
    id: 'PDW',
    loinc: '32207-3',
    canonicalName: { en: 'Platelet Distribution Width', ro: 'Distributia Trombocitara' },
    aliases: ['pdw', 'platelet distribution width', 'largimea distributiei trombocitare'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'fL' },
    referenceRanges: [{ sex: 'any', low: 9, high: 17, unit: 'fL' }],
  },
  {
    id: 'MPV',
    loinc: '32623-1',
    canonicalName: { en: 'Mean Platelet Volume', ro: 'Volum Trombocitar Mediu' },
    aliases: ['mpv', 'volum trombocitar mediu', 'mean platelet volume'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'fL' },
    referenceRanges: [{ sex: 'any', low: 7.5, high: 12.5, unit: 'fL' }],
  },
  {
    id: 'PCT',
    loinc: '13056-7',
    canonicalName: { en: 'Plateletcrit', ro: 'Trombocrit' },
    aliases: ['pct', 'plateletcrit', 'trombocrit', 'plachetocrit'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 0.1, high: 0.5, unit: '%' }],
  },
  {
    id: 'PLCR',
    loinc: '51640-8',
    canonicalName: { en: 'P-LCR', ro: 'P-LCR' },
    aliases: ['p-lcr', 'plcr', 'platelet large cell ratio', 'raport trombocite mari'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 15, high: 35, unit: '%' }],
  },
  {
    id: 'PLCC',
    loinc: null,
    canonicalName: { en: 'P-LCC', ro: 'P-LCC' },
    aliases: ['p-lcc', 'plcc', 'platelet large cell count'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
  },
  {
    id: 'NRBC_ABS',
    loinc: '58413-6',
    canonicalName: { en: 'Nucleated Red Blood Cells Absolute', ro: 'Eritrocite Nucleate Absolute' },
    aliases: ['nrbc#', 'nrbc #', 'nrbc absolute', 'nrbc abs', 'eritrocite nucleate absolute', 'hematii nucleate absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
  },
  {
    id: 'NRBC_PCT',
    loinc: '58412-8',
    canonicalName: { en: 'NRBC Percent', ro: 'Eritrocite Nucleate Procent' },
    aliases: ['nrbc%', 'nrbc %', 'nrbc percent', 'eritrocite nucleate procent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
  },
  {
    id: 'NEUT_ABS',
    loinc: '751-8',
    canonicalName: { en: 'Neutrophils Absolute', ro: 'Neutrofile Absolute' },
    aliases: ['neut#', 'neut #', 'neut abs', 'neutrofile absolute', 'neutrophils absolute', 'granulocite neutrofile absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 1.8, high: 7.5, unit: '×10³/μL' }],
  },
  {
    id: 'NEUT_PCT',
    loinc: '770-8',
    canonicalName: { en: 'Neutrophils Percent', ro: 'Neutrofile Procent' },
    aliases: ['neut%', 'neut %', 'neutrofile procent', 'neutrofile %', 'neutrophils percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 40, high: 75, unit: '%' }],
  },
  {
    id: 'LYMPH_ABS',
    loinc: '731-0',
    canonicalName: { en: 'Lymphocytes Absolute', ro: 'Limfocite Absolute' },
    aliases: ['lymph#', 'lymph #', 'lymph abs', 'limfocite absolute', 'lymphocytes absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 1.0, high: 4.5, unit: '×10³/μL' }],
  },
  {
    id: 'LYMPH_PCT',
    loinc: '736-9',
    canonicalName: { en: 'Lymphocytes Percent', ro: 'Limfocite Procent' },
    aliases: ['lymph%', 'lymph %', 'limfocite procent', 'limfocite %', 'lymphocytes percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 20, high: 45, unit: '%' }],
  },
  {
    id: 'MONO_ABS',
    loinc: '742-7',
    canonicalName: { en: 'Monocytes Absolute', ro: 'Monocite Absolute' },
    aliases: ['mono#', 'mono #', 'mono abs', 'monocite absolute', 'monocytes absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 0.2, high: 1.0, unit: '×10³/μL' }],
  },
  {
    id: 'MONO_PCT',
    loinc: '5905-5',
    canonicalName: { en: 'Monocytes Percent', ro: 'Monocite Procent' },
    aliases: ['mono%', 'mono %', 'monocite procent', 'monocite %', 'monocytes percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 2, high: 10, unit: '%' }],
  },
  {
    id: 'EOS_ABS',
    loinc: '711-2',
    canonicalName: { en: 'Eosinophils Absolute', ro: 'Eozinofile Absolute' },
    aliases: ['eo#', 'eo #', 'eos#', 'eos #', 'eosinofile absolute', 'eozinofile absolute', 'eosinophils absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 0.0, high: 0.5, unit: '×10³/μL' }],
  },
  {
    id: 'EOS_PCT',
    loinc: '713-8',
    canonicalName: { en: 'Eosinophils Percent', ro: 'Eozinofile Procent' },
    aliases: ['eo%', 'eo %', 'eos%', 'eos %', 'eosinofile procent', 'eozinofile procent', 'eosinophils percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 1, high: 6, unit: '%' }],
  },
  {
    id: 'BASO_ABS',
    loinc: '704-5',
    canonicalName: { en: 'Basophils Absolute', ro: 'Bazofile Absolute' },
    aliases: ['baso#', 'baso #', 'baso abs', 'bazofile absolute', 'basophils absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 0.0, high: 0.1, unit: '×10³/μL' }],
  },
  {
    id: 'BASO_PCT',
    loinc: '706-0',
    canonicalName: { en: 'Basophils Percent', ro: 'Bazofile Procent' },
    aliases: ['baso%', 'baso %', 'bazofile procent', 'basophils percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 0, high: 1, unit: '%' }],
  },
  {
    id: 'IG_ABS',
    loinc: '53115-2',
    canonicalName: { en: 'Immature Granulocytes Absolute', ro: 'Granulocite Imature Absolute' },
    aliases: ['ig#', 'ig #', 'ig abs', 'granulocite imature absolute', 'immature granulocytes absolute'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
  },
  {
    id: 'IG_PCT',
    loinc: '71695-1',
    canonicalName: { en: 'Immature Granulocytes Percent', ro: 'Granulocite Imature Procent' },
    aliases: ['ig%', 'ig %', 'granulocite imature procent', 'immature granulocytes percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
  },
  {
    id: 'RETIC_PCT',
    loinc: '17849-1',
    canonicalName: { en: 'Reticulocytes Percent', ro: 'Reticulocite Procent' },
    aliases: ['ret%', 'ret %', 'reticulocite procent', 'reticulocite %', 'reticulocytes percent'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 0.5, high: 2.5, unit: '%' }],
  },
  {
    id: 'RETIC_ABS',
    loinc: '60474-4',
    canonicalName: { en: 'Reticulocytes Absolute', ro: 'Reticulocite Absolute' },
    aliases: ['ret#', 'ret #', 'reticulocite absolute', 'reticulocytes absolute', 'reticulocyte count'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '×10³/μL' },
    referenceRanges: [{ sex: 'any', low: 25, high: 100, unit: '×10³/μL' }],
  },
  {
    id: 'ESR',
    loinc: '30341-2',
    canonicalName: { en: 'ESR', ro: 'VSH' },
    aliases: ['vsh', 'esr', 'viteza de sedimentare a hematiilor', 'erythrocyte sedimentation rate'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: 'mm/h' },
    referenceRanges: [
      { sex: 'M', high: 15, unit: 'mm/h' },
      { sex: 'F', high: 20, unit: 'mm/h' },
    ],
    trendIsClinicallyPrimary: true,
  },

  // =========================================================
  // COAGULARE
  // =========================================================
  {
    id: 'PT',
    loinc: '5902-2',
    canonicalName: { en: 'Prothrombin Time', ro: 'Timp de Protrombina' },
    aliases: ['pt', 'timp de protrombina', 'prothrombin time', 'quick', 'timp quick'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'sec', alternatives: ['s'] },
    referenceRanges: [{ sex: 'any', low: 9.5, high: 13.5, unit: 'sec' }],
  },
  {
    id: 'INR',
    loinc: '34714-6',
    canonicalName: { en: 'INR', ro: 'INR' },
    aliases: ['inr', 'international normalized ratio'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: '' },
    referenceRanges: [{ sex: 'any', low: 0.9, high: 1.1 }],
    criticalBands: [{ high: 5.0 }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'APTT',
    loinc: '3173-2',
    canonicalName: { en: 'APTT', ro: 'APTT' },
    aliases: ['aptt', 'a ptt', 'timp de tromboplastina partial activata', 'activated partial thromboplastin time'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'sec' },
    referenceRanges: [{ sex: 'any', low: 25, high: 35, unit: 'sec' }],
  },
  {
    id: 'FIB',
    loinc: '3255-7',
    canonicalName: { en: 'Fibrinogen', ro: 'Fibrinogen' },
    aliases: ['fibrinogen', 'fibrinogenemie', 'fibrinogen plasma'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['g/L'] },
    referenceRanges: [{ sex: 'any', low: 200, high: 400, unit: 'mg/dL' }],
  },
  {
    id: 'DDIMER',
    loinc: '48065-7',
    canonicalName: { en: 'D-Dimer', ro: 'D-Dimeri' },
    aliases: ['d dimer', 'd-dimer', 'ddimer', 'dimeri d', 'dimer d', 'd dimeri'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'mg/L FEU', alternatives: ['μg/mL FEU', 'ng/mL'] },
    referenceRanges: [{ sex: 'any', high: 0.5, unit: 'mg/L FEU' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'TT',
    loinc: '3243-3',
    canonicalName: { en: 'Thrombin Time', ro: 'Timp Trombina' },
    aliases: ['tt', 'timp trombina', 'thrombin time'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'sec' },
    referenceRanges: [{ sex: 'any', low: 15, high: 19, unit: 'sec' }],
  },
  {
    id: 'AT3',
    loinc: '27818-0',
    canonicalName: { en: 'Antithrombin III', ro: 'Antitrombina III' },
    aliases: ['antitrombina iii', 'antithrombin iii', 'at iii'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 80, high: 120, unit: '%' }],
  },
  {
    id: 'PROTEIN_C',
    loinc: '27820-6',
    canonicalName: { en: 'Protein C', ro: 'Proteina C' },
    aliases: ['proteina c', 'protein c'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 70, high: 140, unit: '%' }],
  },
  {
    id: 'PROTEIN_S',
    loinc: '27821-4',
    canonicalName: { en: 'Protein S', ro: 'Proteina S' },
    aliases: ['proteina s', 'protein s'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [
      { sex: 'M', low: 74, high: 146, unit: '%' },
      { sex: 'F', low: 55, high: 123, unit: '%' },
    ],
  },

  // =========================================================
  // BIOCHIMIE GENERALA
  // =========================================================
  {
    id: 'GLU',
    loinc: '2345-7',
    canonicalName: { en: 'Glucose', ro: 'Glucoza' },
    aliases: ['glucoza', 'glucose', 'glicemie', 'glycemia', 'blood glucose', 'serum glucose', 'glucoza serica'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 70, high: 99, unit: 'mg/dL' }],
    criticalBands: [{ high: 500, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'GLU_CSF',
    loinc: '2342-4',
    canonicalName: { en: 'Glucose (CSF)', ro: 'Glucoza (LCR)' },
    aliases: ['glucoza lcr', 'glucose csf', 'csf glucose', 'glucoza lichid cefalorahidian'],
    specimen: 'csf',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 50, high: 80, unit: 'mg/dL' }],
  },
  {
    id: 'HBA1C',
    loinc: '4548-4',
    canonicalName: { en: 'HbA1c', ro: 'Hemoglobina Glicata' },
    aliases: ['hba1c', 'hemoglobina glicata', 'hemoglobina glicozilata', 'glycated hemoglobin', 'glycosylated hemoglobin'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%', alternatives: ['mmol/mol'] },
    referenceRanges: [{ sex: 'any', high: 5.6, unit: '%' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'UREA',
    loinc: '3094-0',
    canonicalName: { en: 'Urea', ro: 'Uree' },
    aliases: ['uree', 'urea', 'blood urea', 'uree serica', 'azot ureic', 'bun', 'blood urea nitrogen'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 7, high: 20, unit: 'mg/dL' }],
  },
  {
    id: 'CREAT',
    loinc: '2160-0',
    canonicalName: { en: 'Creatinine', ro: 'Creatinina' },
    aliases: ['creatinina', 'creatinine', 'creatinina serica', 'serum creatinine'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['μmol/L'] },
    referenceRanges: [
      { sex: 'M', low: 0.74, high: 1.35, unit: 'mg/dL' },
      { sex: 'F', low: 0.59, high: 1.04, unit: 'mg/dL' },
    ],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'EGFR',
    loinc: '62238-1',
    canonicalName: { en: 'eGFR', ro: 'Rata Filtrarii Glomerulare' },
    aliases: ['egfr', 'e gfr', 'rfg', 'rata filtrarii glomerulare', 'filtrare glomerulara', 'estimated glomerular filtration rate'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mL/min/1.73m²' },
    referenceRanges: [{ sex: 'any', low: 60, unit: 'mL/min/1.73m²' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'UA',
    loinc: '3084-1',
    canonicalName: { en: 'Uric Acid', ro: 'Acid Uric' },
    aliases: ['acid uric', 'uric acid', 'uricemie'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['μmol/L'] },
    referenceRanges: [
      { sex: 'M', low: 3.4, high: 7.0, unit: 'mg/dL' },
      { sex: 'F', low: 2.4, high: 6.0, unit: 'mg/dL' },
    ],
  },
  {
    id: 'TP',
    loinc: '2885-2',
    canonicalName: { en: 'Total Protein', ro: 'Proteine Totale' },
    aliases: ['proteine totale', 'total protein', 'total proteins', 'proteinemie totala'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'g/dL', alternatives: ['g/L'] },
    referenceRanges: [{ sex: 'any', low: 6.4, high: 8.3, unit: 'g/dL' }],
  },
  {
    id: 'ALB',
    loinc: '1751-7',
    canonicalName: { en: 'Albumin', ro: 'Albumina' },
    aliases: ['albumina', 'albumin', 'albumina serica', 'serum albumin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'g/dL', alternatives: ['g/L'] },
    referenceRanges: [{ sex: 'any', low: 3.5, high: 5.0, unit: 'g/dL' }],
  },
  {
    id: 'CA',
    loinc: '17861-6',
    canonicalName: { en: 'Calcium', ro: 'Calciu' },
    aliases: ['calciu', 'calcium', 'ca', 'calciu seric', 'serum calcium'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 8.5, high: 10.5, unit: 'mg/dL' }],
  },
  {
    id: 'CA_ION',
    loinc: '1994-3',
    canonicalName: { en: 'Ionized Calcium', ro: 'Calciu Ionizat' },
    aliases: ['calciu ionic', 'calciu ionizat', 'ionized calcium', 'calcium ionizat', 'ca++', 'ca2+', 'calciu liber'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mmol/L', alternatives: ['mg/dL'] },
    referenceRanges: [{ sex: 'any', low: 1.15, high: 1.35, unit: 'mmol/L' }],
  },
  {
    id: 'MG',
    loinc: '2601-3',
    canonicalName: { en: 'Magnesium', ro: 'Magneziu' },
    aliases: ['magneziu', 'magnesium', 'mg', 'magneziu seric'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L', 'mEq/L'] },
    referenceRanges: [{ sex: 'any', low: 1.7, high: 2.2, unit: 'mg/dL' }],
  },
  {
    id: 'PHOS',
    loinc: '2777-1',
    canonicalName: { en: 'Phosphorus', ro: 'Fosfor' },
    aliases: ['fosfor', 'phosphorus', 'phosphate', 'fosfat', 'fosfor seric'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 2.5, high: 4.5, unit: 'mg/dL' }],
  },
  {
    id: 'NA',
    loinc: '2951-2',
    canonicalName: { en: 'Sodium', ro: 'Sodiu' },
    aliases: ['sodiu', 'sodium', 'na', 'natriu', 'serum sodium'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mEq/L', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 136, high: 145, unit: 'mEq/L' }],
    criticalBands: [{ low: 125, high: 155, unit: 'mEq/L' }],
  },
  {
    id: 'K',
    loinc: '2823-3',
    canonicalName: { en: 'Potassium', ro: 'Potasiu' },
    aliases: ['potasiu', 'potassium', 'k', 'kalium', 'serum potassium'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mEq/L', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 3.5, high: 5.0, unit: 'mEq/L' }],
    criticalBands: [{ low: 2.5, high: 6.5, unit: 'mEq/L' }],
  },
  {
    id: 'CL',
    loinc: '2075-0',
    canonicalName: { en: 'Chloride', ro: 'Cloruri' },
    aliases: ['clor', 'cloruri', 'chloride', 'cl', 'serum chloride'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mEq/L', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 98, high: 106, unit: 'mEq/L' }],
  },
  {
    id: 'HCO3',
    loinc: '1959-6',
    canonicalName: { en: 'Bicarbonate', ro: 'Bicarbonat' },
    aliases: ['bicarbonat', 'bicarbonate', 'hco3', 'co2 total'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mEq/L', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', low: 22, high: 29, unit: 'mEq/L' }],
  },
  {
    id: 'FE',
    loinc: '2498-4',
    canonicalName: { en: 'Iron', ro: 'Fier' },
    aliases: ['fier', 'iron', 'sideremie', 'serum iron', 'fier seric'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/dL', alternatives: ['μmol/L'] },
    referenceRanges: [
      { sex: 'M', low: 60, high: 170, unit: 'μg/dL' },
      { sex: 'F', low: 50, high: 170, unit: 'μg/dL' },
    ],
  },
  {
    id: 'FERR',
    loinc: '2276-4',
    canonicalName: { en: 'Ferritin', ro: 'Feritina' },
    aliases: ['feritina', 'ferritin', 'serum ferritin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['μg/L'] },
    referenceRanges: [
      { sex: 'M', low: 24, high: 336, unit: 'ng/mL' },
      { sex: 'F', low: 11, high: 307, unit: 'ng/mL' },
    ],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'TRANSF',
    loinc: '3034-6',
    canonicalName: { en: 'Transferrin', ro: 'Transferina' },
    aliases: ['transferina', 'transferrin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['g/L'] },
    referenceRanges: [{ sex: 'any', low: 200, high: 360, unit: 'mg/dL' }],
  },
  {
    id: 'TIBC',
    loinc: '2500-7',
    canonicalName: { en: 'TIBC', ro: 'Capacitate Totala de Legare a Fierului' },
    aliases: ['tibc', 'capacitate totala de legare a fierului', 'total iron binding capacity'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/dL' },
    referenceRanges: [{ sex: 'any', low: 250, high: 370, unit: 'μg/dL' }],
  },
  {
    id: 'TSAT',
    loinc: null,
    canonicalName: { en: 'Transferrin Saturation', ro: 'Saturatia Transferinei' },
    aliases: ['saturatia transferinei', 'transferrin saturation', 'tsat', 'sat transferina'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: '%' },
    referenceRanges: [{ sex: 'any', low: 20, high: 50, unit: '%' }],
  },
  {
    id: 'B12',
    loinc: '2132-9',
    canonicalName: { en: 'Vitamin B12', ro: 'Vitamina B12' },
    aliases: ['vitamina b12', 'b12', 'cobalamina', 'vitamin b12'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 200, high: 900, unit: 'pg/mL' }],
  },
  {
    id: 'FOLATE',
    loinc: '2284-9',
    canonicalName: { en: 'Folate', ro: 'Acid Folic' },
    aliases: ['folat', 'folate', 'acid folic', 'folic acid'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['nmol/L'] },
    referenceRanges: [{ sex: 'any', low: 3, high: 17, unit: 'ng/mL' }],
  },
  {
    id: 'VITD',
    loinc: '35365-6',
    canonicalName: { en: 'Vitamin D', ro: 'Vitamina D' },
    aliases: ['vitamina d', 'vitamin d', '25 oh vitamina d', '25-oh vitamin d', '25 hydroxy vitamin d', '25 hidroxivitamina d', '25 oh d'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['nmol/L'] },
    referenceRanges: [{ sex: 'any', low: 30, high: 100, unit: 'ng/mL' }],
  },
  {
    id: 'ALT',
    loinc: '1742-6',
    canonicalName: { en: 'ALT', ro: 'ALT' },
    aliases: ['alt', 'alat', 'gpt', 'tgp', 'alanin aminotransferaza', 'alanine aminotransferase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', high: 40, unit: 'U/L' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'AST',
    loinc: '1920-8',
    canonicalName: { en: 'AST', ro: 'AST' },
    aliases: ['ast', 'asat', 'got', 'tgo', 'aspartat aminotransferaza', 'aspartate aminotransferase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', high: 40, unit: 'U/L' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'GGT',
    loinc: '2324-2',
    canonicalName: { en: 'GGT', ro: 'GGT' },
    aliases: ['ggt', 'gama gt', 'gamma gt', 'gama glutamil transferaza', 'gamma glutamyl transferase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [
      { sex: 'M', high: 61, unit: 'U/L' },
      { sex: 'F', high: 36, unit: 'U/L' },
    ],
  },
  {
    id: 'ALP',
    loinc: '6768-6',
    canonicalName: { en: 'Alkaline Phosphatase', ro: 'Fosfataza Alcalina' },
    aliases: ['fosfataza alcalina', 'alkaline phosphatase', 'alp', 'fal'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', low: 44, high: 147, unit: 'U/L' }],
  },
  {
    id: 'LDH',
    loinc: '14804-9',
    canonicalName: { en: 'LDH', ro: 'LDH' },
    aliases: ['ldh', 'lactat dehidrogenaza', 'lactate dehydrogenase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', low: 140, high: 280, unit: 'U/L' }],
  },
  {
    id: 'CK',
    loinc: '2157-6',
    canonicalName: { en: 'CK', ro: 'CK' },
    aliases: ['ck', 'cpk', 'creatin kinaza', 'creatine kinase', 'creatin phosphokinase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [
      { sex: 'M', high: 174, unit: 'U/L' },
      { sex: 'F', high: 140, unit: 'U/L' },
    ],
  },
  {
    id: 'CKMB',
    loinc: '13969-1',
    canonicalName: { en: 'CK-MB', ro: 'CK-MB' },
    aliases: ['ck mb', 'ck-mb', 'creatin kinaza mb', 'creatine kinase mb'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['U/L'] },
    referenceRanges: [{ sex: 'any', high: 6.3, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'TROPONIN',
    loinc: '10839-9',
    canonicalName: { en: 'Troponin I', ro: 'Troponina I' },
    aliases: ['troponin i', 'troponina i', 'cardiac troponin i', 'troponin', 'troponina'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['μg/L'] },
    referenceRanges: [{ sex: 'any', high: 0.04, unit: 'ng/mL' }],
    criticalBands: [{ high: 0.04, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'TROPONIN_T',
    loinc: '6598-7',
    canonicalName: { en: 'Troponin T', ro: 'Troponina T' },
    aliases: ['troponin t', 'troponina t', 'cardiac troponin t', 'hs troponin t', 'high sensitivity troponin t'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/L', alternatives: ['pg/mL'] },
    referenceRanges: [{ sex: 'any', high: 19, unit: 'ng/L' }],
    criticalBands: [{ high: 19, unit: 'ng/L' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'AMY',
    loinc: '1798-8',
    canonicalName: { en: 'Amylase', ro: 'Amilaza' },
    aliases: ['amilaza', 'amylase', 'amilaza serica'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', low: 30, high: 110, unit: 'U/L' }],
  },
  {
    id: 'LIP',
    loinc: '3040-3',
    canonicalName: { en: 'Lipase', ro: 'Lipaza' },
    aliases: ['lipaza', 'lipase'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    referenceRanges: [{ sex: 'any', low: 13, high: 60, unit: 'U/L' }],
  },
  {
    id: 'TBIL',
    loinc: '1975-2',
    canonicalName: { en: 'Total Bilirubin', ro: 'Bilirubina Totala' },
    aliases: ['bilirubina totala', 'total bilirubin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['μmol/L'] },
    referenceRanges: [{ sex: 'any', low: 0.3, high: 1.2, unit: 'mg/dL' }],
  },
  {
    id: 'DBIL',
    loinc: '1968-7',
    canonicalName: { en: 'Direct Bilirubin', ro: 'Bilirubina Directa' },
    aliases: ['bilirubina directa', 'direct bilirubin', 'conjugated bilirubin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', high: 0.3, unit: 'mg/dL' }],
  },
  {
    id: 'IBIL',
    loinc: '1971-1',
    canonicalName: { en: 'Indirect Bilirubin', ro: 'Bilirubina Indirecta' },
    aliases: ['bilirubina indirecta', 'indirect bilirubin', 'unconjugated bilirubin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 0.2, high: 1.2, unit: 'mg/dL' }],
  },
  {
    id: 'CHOL',
    loinc: '2093-3',
    canonicalName: { en: 'Total Cholesterol', ro: 'Colesterol Total' },
    aliases: ['colesterol total', 'total cholesterol', 'cholesterol total'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', high: 200, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HDL',
    loinc: '2085-9',
    canonicalName: { en: 'HDL Cholesterol', ro: 'Colesterol HDL' },
    aliases: ['hdl', 'hdl colesterol', 'hdl cholesterol', 'colesterol hdl'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [
      { sex: 'M', low: 40, unit: 'mg/dL' },
      { sex: 'F', low: 50, unit: 'mg/dL' },
    ],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'LDL',
    loinc: '2089-1',
    canonicalName: { en: 'LDL Cholesterol', ro: 'Colesterol LDL' },
    aliases: ['ldl', 'ldl colesterol', 'ldl cholesterol', 'colesterol ldl'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', high: 100, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'VLDL',
    loinc: null,
    canonicalName: { en: 'VLDL Cholesterol', ro: 'Colesterol VLDL' },
    aliases: ['vldl', 'vldl colesterol', 'vldl cholesterol'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 5, high: 40, unit: 'mg/dL' }],
  },
  {
    id: 'TG',
    loinc: '2571-8',
    canonicalName: { en: 'Triglycerides', ro: 'Trigliceride' },
    aliases: ['trigliceride', 'triglycerides', 'tg'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mmol/L'] },
    referenceRanges: [{ sex: 'any', high: 150, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'APOA1',
    loinc: null,
    canonicalName: { en: 'Apolipoprotein A1', ro: 'Apolipoproteina A1' },
    aliases: ['apolipoproteina a1', 'apoa1', 'apo a1', 'apolipoprotein a1'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [
      { sex: 'M', low: 110, high: 180, unit: 'mg/dL' },
      { sex: 'F', low: 108, high: 215, unit: 'mg/dL' },
    ],
  },
  {
    id: 'APOB',
    loinc: null,
    canonicalName: { en: 'Apolipoprotein B', ro: 'Apolipoproteina B' },
    aliases: ['apolipoproteina b', 'apob', 'apo b', 'apolipoprotein b'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [
      { sex: 'M', low: 66, high: 133, unit: 'mg/dL' },
      { sex: 'F', low: 60, high: 117, unit: 'mg/dL' },
    ],
  },
  {
    id: 'LPA',
    loinc: null,
    canonicalName: { en: 'Lipoprotein(a)', ro: 'Lipoproteina(a)' },
    aliases: ['lipoproteina a', 'lipoprotein a', 'lp a', 'lp(a)'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['nmol/L'] },
    referenceRanges: [{ sex: 'any', high: 30, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },

  // =========================================================
  // IMUNOLOGIE / SEROLOGIE / INFLAMATIE
  // =========================================================
  {
    id: 'CRP',
    loinc: '1988-5',
    canonicalName: { en: 'CRP', ro: 'Proteina C Reactiva' },
    aliases: ['crp', 'proteina c reactiva', 'c reactive protein'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL', alternatives: ['mg/L'] },
    referenceRanges: [{ sex: 'any', high: 1.0, unit: 'mg/dL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HSCRP',
    loinc: '30522-7',
    canonicalName: { en: 'High Sensitivity CRP', ro: 'CRP Ultrasensibil' },
    aliases: ['hs crp', 'hs-crp', 'crp ultrasensibil', 'crp inalta sensibilitate', 'high sensitivity crp'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/L' },
    referenceRanges: [{ sex: 'any', high: 1.0, unit: 'mg/L' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'PCT_INFLAM',
    loinc: '33959-8',
    canonicalName: { en: 'Procalcitonin', ro: 'Procalcitonina' },
    aliases: ['procalcitonina', 'procalcitonin', 'pct procalcitonin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['μg/L'] },
    referenceRanges: [{ sex: 'any', high: 0.1, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'RF',
    loinc: null,
    canonicalName: { en: 'Rheumatoid Factor', ro: 'Factor Reumatoid' },
    aliases: ['factor reumatoid', 'rheumatoid factor', 'rf'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    referenceRanges: [{ sex: 'any', high: 14, unit: 'IU/mL' }],
  },
  {
    id: 'ANTICCP',
    loinc: null,
    canonicalName: { en: 'Anti-CCP', ro: 'Anti-CCP' },
    aliases: ['anti ccp', 'anti-ccp', 'anticorpi anti ccp', 'ccp antibodies'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/mL' },
    referenceRanges: [{ sex: 'any', high: 20, unit: 'U/mL' }],
  },
  {
    id: 'ANA',
    loinc: null,
    canonicalName: { en: 'ANA', ro: 'Anticorpi Antinucleari' },
    aliases: ['ana', 'anticorpi antinucleari', 'antinuclear antibodies'],
    specimen: 'serum',
    valueType: 'semi_quantitative',
    units: { preferred: 'titer' },
    referenceRanges: [{ text: 'Negative (<1:40)' }],
    interpretationField: 'optional',
  },
  {
    id: 'ANTI_DSDNA',
    loinc: null,
    canonicalName: { en: 'Anti-dsDNA', ro: 'Anti-ADN dublu catenar' },
    aliases: ['anti dsdna', 'anti-dsdna', 'anticorpi anti adn dublu catenar', 'double stranded dna antibodies'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    referenceRanges: [{ sex: 'any', high: 10, unit: 'IU/mL' }],
  },
  {
    id: 'IGA',
    loinc: null,
    canonicalName: { en: 'IgA', ro: 'Imunoglobulina A' },
    aliases: ['iga', 'imunoglobulina a', 'immunoglobulin a'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 90, high: 400, unit: 'mg/dL' }],
  },
  {
    id: 'IGG',
    loinc: null,
    canonicalName: { en: 'IgG', ro: 'Imunoglobulina G' },
    aliases: ['igg', 'imunoglobulina g', 'immunoglobulin g'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 700, high: 1600, unit: 'mg/dL' }],
  },
  {
    id: 'IGM',
    loinc: null,
    canonicalName: { en: 'IgM', ro: 'Imunoglobulina M' },
    aliases: ['igm', 'imunoglobulina m', 'immunoglobulin m'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [
      { sex: 'M', low: 40, high: 230, unit: 'mg/dL' },
      { sex: 'F', low: 50, high: 300, unit: 'mg/dL' },
    ],
  },
  {
    id: 'IGE',
    loinc: null,
    canonicalName: { en: 'IgE', ro: 'Imunoglobulina E' },
    aliases: ['ige', 'imunoglobulina e', 'immunoglobulin e'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    referenceRanges: [{ sex: 'any', high: 100, unit: 'IU/mL' }],
  },
  {
    id: 'C3',
    loinc: null,
    canonicalName: { en: 'C3 Complement', ro: 'Complement C3' },
    aliases: ['c3', 'complement c3'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 90, high: 180, unit: 'mg/dL' }],
  },
  {
    id: 'C4',
    loinc: null,
    canonicalName: { en: 'C4 Complement', ro: 'Complement C4' },
    aliases: ['c4', 'complement c4'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    referenceRanges: [{ sex: 'any', low: 16, high: 47, unit: 'mg/dL' }],
  },

  // Serology — qualitative
  {
    id: 'HBSAG',
    loinc: '5196-1',
    canonicalName: { en: 'HBsAg', ro: 'Antigen HBs' },
    aliases: ['hbsag', 'antigen hbs', 'hepatita b antigen de suprafata', 'hepatitis b surface antigen'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
    interpretationField: 'optional',
  },
  {
    id: 'ANTI_HBS',
    loinc: null,
    canonicalName: { en: 'Anti-HBs', ro: 'Anti-HBs' },
    aliases: ['anti hbs', 'anti-hbs', 'anticorpi anti hbs', 'hepatitis b surface antibody'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mIU/mL' },
    referenceRanges: [{ text: 'Protective ≥10 mIU/mL' }],
  },
  {
    id: 'ANTI_HBC',
    loinc: null,
    canonicalName: { en: 'Anti-HBc', ro: 'Anti-HBc' },
    aliases: ['anti hbc', 'anti-hbc', 'anticorpi anti hbc', 'hepatitis b core antibody'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'ANTI_HCV',
    loinc: '16128-1',
    canonicalName: { en: 'Anti-HCV', ro: 'Anti-HCV' },
    aliases: ['anti hcv', 'anti-hcv', 'anticorpi anti hcv', 'hepatitis c antibody'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
    interpretationField: 'optional',
  },
  {
    id: 'HIV',
    loinc: '75622-1',
    canonicalName: { en: 'HIV Ag/Ab', ro: 'HIV Ag/Ac' },
    aliases: ['hiv', 'hiv ag ab', 'hiv 1 2', 'hiv combo', 'hiv antigen anticorp', 'hiv antigen antibody'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
    interpretationField: 'optional',
  },
  {
    id: 'VDRL',
    loinc: null,
    canonicalName: { en: 'VDRL', ro: 'VDRL / RPR' },
    aliases: ['vdrl', 'rpr', 'sifilis', 'syphilis'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'TPHA',
    loinc: null,
    canonicalName: { en: 'TPHA', ro: 'TPHA' },
    aliases: ['tpha', 'tppa', 'treponema pallidum'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'TOXO_IGG',
    loinc: null,
    canonicalName: { en: 'Toxoplasma IgG', ro: 'Toxoplasma IgG' },
    aliases: ['toxoplasma igg', 'toxoplasma gondii igg'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'TOXO_IGM',
    loinc: null,
    canonicalName: { en: 'Toxoplasma IgM', ro: 'Toxoplasma IgM' },
    aliases: ['toxoplasma igm', 'toxoplasma gondii igm'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'RUBELLA_IGG',
    loinc: null,
    canonicalName: { en: 'Rubella IgG', ro: 'Rubeola IgG' },
    aliases: ['rubella igg', 'rubeola igg'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'RUBELLA_IGM',
    loinc: null,
    canonicalName: { en: 'Rubella IgM', ro: 'Rubeola IgM' },
    aliases: ['rubella igm', 'rubeola igm'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'CMV_IGG',
    loinc: null,
    canonicalName: { en: 'CMV IgG', ro: 'CMV IgG' },
    aliases: ['cmv igg', 'citomegalovirus igg', 'cytomegalovirus igg'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'CMV_IGM',
    loinc: null,
    canonicalName: { en: 'CMV IgM', ro: 'CMV IgM' },
    aliases: ['cmv igm', 'citomegalovirus igm', 'cytomegalovirus igm'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'EBV_VCA_IGG',
    loinc: null,
    canonicalName: { en: 'EBV VCA IgG', ro: 'EBV VCA IgG' },
    aliases: ['ebv vca igg', 'epstein barr vca igg'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },
  {
    id: 'EBV_VCA_IGM',
    loinc: null,
    canonicalName: { en: 'EBV VCA IgM', ro: 'EBV VCA IgM' },
    aliases: ['ebv vca igm', 'epstein barr vca igm'],
    specimen: 'serum',
    valueType: 'qualitative',
    qualitativeValues: ['Reactive', 'Non-reactive'],
  },

  // =========================================================
  // ENDOCRINOLOGIE
  // =========================================================
  {
    id: 'TSH',
    loinc: '3016-3',
    canonicalName: { en: 'TSH', ro: 'TSH' },
    aliases: ['tsh', 'tirotropina', 'thyroid stimulating hormone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mIU/L', alternatives: ['μIU/mL'] },
    referenceRanges: [{ sex: 'any', low: 0.27, high: 4.2, unit: 'mIU/L' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'FT4',
    loinc: '3024-7',
    canonicalName: { en: 'Free T4', ro: 'T4 Liber' },
    aliases: ['ft4', 'free t4', 't4 liber', 'tiroxina libera'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/dL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 0.93, high: 1.7, unit: 'ng/dL' }],
  },
  {
    id: 'FT3',
    loinc: '3051-0',
    canonicalName: { en: 'Free T3', ro: 'T3 Liber' },
    aliases: ['ft3', 'free t3', 't3 liber', 'triiodotironina libera'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 2.0, high: 4.4, unit: 'pg/mL' }],
  },
  {
    id: 'T4_TOTAL',
    loinc: null,
    canonicalName: { en: 'Total T4', ro: 'T4 Total' },
    aliases: ['t4 total', 'total t4', 'tiroxina totala'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/dL' },
    referenceRanges: [{ sex: 'any', low: 5.1, high: 14.1, unit: 'μg/dL' }],
  },
  {
    id: 'T3_TOTAL',
    loinc: null,
    canonicalName: { en: 'Total T3', ro: 'T3 Total' },
    aliases: ['t3 total', 'total t3', 'triiodotironina totala'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', low: 0.8, high: 2.0, unit: 'ng/mL' }],
  },
  {
    id: 'ANTI_TPO',
    loinc: '8099-7',
    canonicalName: { en: 'Anti-TPO', ro: 'Anti-TPO' },
    aliases: ['anti tpo', 'anti-tpo', 'anticorpi anti tpo', 'thyroid peroxidase antibodies'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    referenceRanges: [{ sex: 'any', high: 9, unit: 'IU/mL' }],
  },
  {
    id: 'ANTI_TG',
    loinc: null,
    canonicalName: { en: 'Anti-Thyroglobulin', ro: 'Anti-Tiroglobulina' },
    aliases: ['anti tiroglobulina', 'anti-thyroglobulin', 'anti tg', 'anticorpi anti tiroglobulina'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    referenceRanges: [{ sex: 'any', high: 4, unit: 'IU/mL' }],
  },
  {
    id: 'TRAB',
    loinc: null,
    canonicalName: { en: 'TRAb', ro: 'Anticorpi Anti-Receptor TSH' },
    aliases: ['trab', 'anti receptor tsh', 'tsh receptor antibodies'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/L' },
    referenceRanges: [{ sex: 'any', high: 1.75, unit: 'IU/L' }],
  },
  {
    id: 'PTH',
    loinc: '2731-8',
    canonicalName: { en: 'PTH', ro: 'Parathormon' },
    aliases: ['pth', 'parathormon', 'parathyroid hormone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 15, high: 65, unit: 'pg/mL' }],
  },
  {
    id: 'CORTISOL',
    loinc: '2143-6',
    canonicalName: { en: 'Cortisol', ro: 'Cortizol' },
    aliases: ['cortizol', 'cortisol'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/dL', alternatives: ['nmol/L'] },
    referenceRanges: [{ sex: 'any', low: 6.2, high: 19.4, unit: 'μg/dL', text: 'Morning (8am)' }],
  },
  {
    id: 'ACTH',
    loinc: null,
    canonicalName: { en: 'ACTH', ro: 'ACTH' },
    aliases: ['acth', 'adrenocorticotrop', 'adrenocorticotropic hormone'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL' },
    referenceRanges: [{ sex: 'any', low: 7.2, high: 63.3, unit: 'pg/mL', text: 'Morning' }],
  },
  {
    id: 'INSULIN',
    loinc: null,
    canonicalName: { en: 'Insulin', ro: 'Insulina' },
    aliases: ['insulina', 'insulin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μIU/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 2.6, high: 24.9, unit: 'μIU/mL', text: 'Fasting' }],
  },
  {
    id: 'CPEP',
    loinc: null,
    canonicalName: { en: 'C-Peptide', ro: 'Peptid C' },
    aliases: ['c peptid', 'c-peptide', 'peptid c'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', low: 0.78, high: 5.19, unit: 'ng/mL' }],
  },
  {
    id: 'FSH',
    loinc: null,
    canonicalName: { en: 'FSH', ro: 'FSH' },
    aliases: ['fsh', 'follicle stimulating hormone', 'hormon foliculostimulant'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mIU/mL' },
    referenceRanges: [{ text: 'Varies by sex and cycle phase' }],
  },
  {
    id: 'LH',
    loinc: null,
    canonicalName: { en: 'LH', ro: 'LH' },
    aliases: ['lh', 'luteinizing hormone', 'hormon luteinizant'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mIU/mL' },
    referenceRanges: [{ text: 'Varies by sex and cycle phase' }],
  },
  {
    id: 'E2',
    loinc: null,
    canonicalName: { en: 'Estradiol', ro: 'Estradiol' },
    aliases: ['estradiol', 'e2', 'estradiol seric'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ text: 'Varies by sex and cycle phase' }],
  },
  {
    id: 'PROG',
    loinc: null,
    canonicalName: { en: 'Progesterone', ro: 'Progesteron' },
    aliases: ['progesteron', 'progesterone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['nmol/L'] },
    referenceRanges: [{ text: 'Varies by cycle phase' }],
  },
  {
    id: 'PRL',
    loinc: null,
    canonicalName: { en: 'Prolactin', ro: 'Prolactina' },
    aliases: ['prolactina', 'prolactin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL', alternatives: ['μg/L'] },
    referenceRanges: [
      { sex: 'M', low: 4, high: 15, unit: 'ng/mL' },
      { sex: 'F', low: 4, high: 23, unit: 'ng/mL' },
    ],
  },
  {
    id: 'TESTO',
    loinc: null,
    canonicalName: { en: 'Testosterone', ro: 'Testosteron Total' },
    aliases: ['testosteron', 'testosterone', 'testosteron total', 'total testosterone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/dL', alternatives: ['nmol/L'] },
    referenceRanges: [
      { sex: 'M', low: 264, high: 916, unit: 'ng/dL' },
      { sex: 'F', low: 8, high: 48, unit: 'ng/dL' },
    ],
  },
  {
    id: 'FREE_TESTO',
    loinc: null,
    canonicalName: { en: 'Free Testosterone', ro: 'Testosteron Liber' },
    aliases: ['testosteron liber', 'free testosterone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL' },
    referenceRanges: [
      { sex: 'M', low: 8.7, high: 25.1, unit: 'pg/mL' },
      { sex: 'F', high: 2.2, unit: 'pg/mL' },
    ],
  },
  {
    id: 'DHEAS',
    loinc: null,
    canonicalName: { en: 'DHEA-S', ro: 'DHEA-S' },
    aliases: ['dhea s', 'dhea-s', 'dehidroepiandrosteron sulfat', 'dehydroepiandrosterone sulfate'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/dL', alternatives: ['μmol/L'] },
    referenceRanges: [
      { sex: 'M', low: 80, high: 560, unit: 'μg/dL' },
      { sex: 'F', low: 45, high: 380, unit: 'μg/dL' },
    ],
  },
  {
    id: 'SHBG',
    loinc: null,
    canonicalName: { en: 'SHBG', ro: 'SHBG' },
    aliases: ['shbg', 'sex hormone binding globulin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'nmol/L' },
    referenceRanges: [
      { sex: 'M', low: 16, high: 72, unit: 'nmol/L' },
      { sex: 'F', low: 16, high: 119, unit: 'nmol/L' },
    ],
  },
  {
    id: 'OH17PROG',
    loinc: null,
    canonicalName: { en: '17-OH Progesterone', ro: '17-OH Progesteron' },
    aliases: ['17 oh progesteron', '17-oh progesterone', '17 hydroxyprogesterone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [
      { sex: 'M', low: 0.6, high: 3.4, unit: 'ng/mL' },
      { sex: 'F', low: 0.1, high: 0.8, unit: 'ng/mL', text: 'Follicular' },
    ],
  },
  {
    id: 'ALDO',
    loinc: null,
    canonicalName: { en: 'Aldosterone', ro: 'Aldosteron' },
    aliases: ['aldosteron', 'aldosterone'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL', alternatives: ['pmol/L'] },
    referenceRanges: [{ sex: 'any', low: 3.0, high: 35.3, unit: 'pg/mL', text: 'Upright' }],
  },
  {
    id: 'RENIN',
    loinc: null,
    canonicalName: { en: 'Renin', ro: 'Renina' },
    aliases: ['renina', 'renin'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'mIU/L', alternatives: ['pg/mL'] },
  },
  {
    id: 'GH',
    loinc: null,
    canonicalName: { en: 'Growth Hormone', ro: 'Hormon de Crestere' },
    aliases: ['hormon de crestere', 'growth hormone', 'gh', 'somatotrop'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 3.0, unit: 'ng/mL', text: 'Random' }],
  },
  {
    id: 'IGF1',
    loinc: null,
    canonicalName: { en: 'IGF-1', ro: 'IGF-1' },
    aliases: ['igf 1', 'igf-1', 'insulin like growth factor 1'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ text: 'Age-dependent' }],
    trendIsClinicallyPrimary: true,
  },

  // =========================================================
  // MARKERI TUMORALI
  // =========================================================
  {
    id: 'PSA_T',
    loinc: '2857-1',
    canonicalName: { en: 'PSA Total', ro: 'PSA Total' },
    aliases: ['psa total', 'total psa', 'antigen specific prostatic total'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'M', high: 4.0, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'PSA_F',
    loinc: '10886-0',
    canonicalName: { en: 'PSA Free', ro: 'PSA Liber' },
    aliases: ['psa liber', 'free psa', 'psa free'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    interpretationField: 'optional',
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CEA',
    loinc: '2039-6',
    canonicalName: { en: 'CEA', ro: 'Antigen Carcinoembrionar' },
    aliases: ['cea', 'antigen carcinoembrionar', 'carcinoembryonic antigen'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 3.0, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CA199',
    loinc: '24108-3',
    canonicalName: { en: 'CA 19-9', ro: 'CA 19-9' },
    aliases: ['ca 19 9', 'ca19-9', 'ca 19-9'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/mL' },
    referenceRanges: [{ sex: 'any', high: 37, unit: 'U/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CA125',
    loinc: '10334-1',
    canonicalName: { en: 'CA 125', ro: 'CA 125' },
    aliases: ['ca 125', 'ca-125'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/mL' },
    referenceRanges: [{ sex: 'any', high: 35, unit: 'U/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CA153',
    loinc: '6875-9',
    canonicalName: { en: 'CA 15-3', ro: 'CA 15-3' },
    aliases: ['ca 15 3', 'ca15-3', 'ca 15-3'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/mL' },
    referenceRanges: [{ sex: 'any', high: 31.3, unit: 'U/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'AFP',
    loinc: '1834-1',
    canonicalName: { en: 'AFP', ro: 'Alfa-Fetoproteina' },
    aliases: ['afp', 'alfa fetoproteina', 'alpha fetoprotein'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 8.1, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'BHCG',
    loinc: '21198-7',
    canonicalName: { en: 'Beta-hCG', ro: 'Beta-hCG' },
    aliases: ['beta hcg', 'beta-hcg', 'hcg beta', 'gonadotropina corionica beta'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mIU/mL' },
    referenceRanges: [{ sex: 'any', high: 5, unit: 'mIU/mL', text: 'Non-pregnant' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'NSE',
    loinc: null,
    canonicalName: { en: 'NSE', ro: 'Enolaza Neuron-Specifica' },
    aliases: ['nse', 'neuron specific enolase', 'enolaza neuron specifica'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 16.3, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CYFRA',
    loinc: null,
    canonicalName: { en: 'CYFRA 21-1', ro: 'CYFRA 21-1' },
    aliases: ['cyfra 21 1', 'cyfra 21-1'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 3.3, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HE4',
    loinc: null,
    canonicalName: { en: 'HE4', ro: 'HE4' },
    aliases: ['he4', 'human epididymis protein 4'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pmol/L' },
    referenceRanges: [
      { sex: 'F', high: 70, unit: 'pmol/L', text: 'Pre-menopausal' },
      { sex: 'F', high: 140, unit: 'pmol/L', text: 'Post-menopausal' },
    ],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'TG_TUMOR',
    loinc: null,
    canonicalName: { en: 'Thyroglobulin', ro: 'Tiroglobulina' },
    aliases: ['tiroglobulina', 'thyroglobulin', 'tg tumor marker'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 55, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CALCITONIN',
    loinc: null,
    canonicalName: { en: 'Calcitonin', ro: 'Calcitonina' },
    aliases: ['calcitonina', 'calcitonin'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'pg/mL' },
    referenceRanges: [
      { sex: 'M', high: 11.5, unit: 'pg/mL' },
      { sex: 'F', high: 4.6, unit: 'pg/mL' },
    ],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'CHGA',
    loinc: null,
    canonicalName: { en: 'Chromogranin A', ro: 'Cromogranina A' },
    aliases: ['cromogranina a', 'chromogranin a', 'cga'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'ng/mL' },
    referenceRanges: [{ sex: 'any', high: 94, unit: 'ng/mL' }],
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'S100',
    loinc: null,
    canonicalName: { en: 'S100', ro: 'Proteina S100' },
    aliases: ['s100', 'proteina s100', 's-100'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'μg/L' },
    referenceRanges: [{ sex: 'any', high: 0.1, unit: 'μg/L' }],
    trendIsClinicallyPrimary: true,
  },

  // =========================================================
  // BIOLOGIE MOLECULARA
  // =========================================================
  {
    id: 'SARS2_RNA',
    loinc: null,
    canonicalName: { en: 'SARS-CoV-2 RNA', ro: 'ARN SARS-CoV-2' },
    aliases: ['sars cov 2', 'sars-cov-2', 'covid pcr', 'covid rt pcr', 'arn sars cov 2', 'sars cov 2 rna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
    interpretationField: 'optional',
  },
  {
    id: 'RESP_PANEL',
    loinc: null,
    canonicalName: { en: 'Respiratory Virus Panel', ro: 'Panou Virusuri Respiratorii' },
    aliases: ['panou respirator', 'respiratory panel', 'resp panel pcr'],
    specimen: 'swab',
    valueType: 'panel',
    panelMembers: ['SARS2_RNA', 'INFLA_RNA', 'INFLB_RNA', 'RSV_RNA'],
    interpretationField: 'expected',
  },
  {
    id: 'INFLA_RNA',
    loinc: null,
    canonicalName: { en: 'Influenza A RNA', ro: 'ARN Influenza A' },
    aliases: ['influenza a', 'virus gripal a', 'arn influenza a', 'influenza a rna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'INFLB_RNA',
    loinc: null,
    canonicalName: { en: 'Influenza B RNA', ro: 'ARN Influenza B' },
    aliases: ['influenza b', 'virus gripal b', 'arn influenza b', 'influenza b rna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'RSV_RNA',
    loinc: null,
    canonicalName: { en: 'RSV RNA', ro: 'ARN VRS' },
    aliases: ['rsv', 'virus sincitial respirator', 'respiratory syncytial virus', 'rsv rna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'HBV_DNA',
    loinc: null,
    canonicalName: { en: 'HBV DNA', ro: 'ADN HBV' },
    aliases: ['hbv dna', 'adn hbv', 'viremie hbv', 'hepatita b adn', 'hepatitis b dna'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL', alternatives: ['copies/mL'] },
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HCV_RNA',
    loinc: null,
    canonicalName: { en: 'HCV RNA', ro: 'ARN HCV' },
    aliases: ['hcv rna', 'arn hcv', 'viremie hcv', 'hepatita c arn', 'hepatitis c rna'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'IU/mL' },
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HIV_RNA',
    loinc: null,
    canonicalName: { en: 'HIV RNA', ro: 'ARN HIV' },
    aliases: ['hiv rna', 'arn hiv', 'viremie hiv', 'hiv viral load'],
    specimen: 'plasma',
    valueType: 'quantitative',
    units: { preferred: 'copies/mL' },
    trendIsClinicallyPrimary: true,
  },
  {
    id: 'HPV_DNA',
    loinc: null,
    canonicalName: { en: 'HPV DNA', ro: 'ADN HPV' },
    aliases: ['hpv dna', 'adn hpv', 'genotipare hpv', 'hpv genotyping', 'hpv high risk'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
    interpretationField: 'optional',
  },
  {
    id: 'CT_DNA',
    loinc: null,
    canonicalName: { en: 'Chlamydia trachomatis DNA', ro: 'Chlamydia trachomatis ADN' },
    aliases: ['chlamydia trachomatis', 'ct dna', 'adn chlamydia', 'chlamydia dna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'NG_DNA',
    loinc: null,
    canonicalName: { en: 'Neisseria gonorrhoeae DNA', ro: 'Neisseria gonorrhoeae ADN' },
    aliases: ['neisseria gonorrhoeae', 'ng dna', 'adn gonoree', 'gonorrhea dna', 'gonococ dna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'MG_DNA',
    loinc: null,
    canonicalName: { en: 'Mycoplasma genitalium DNA', ro: 'Mycoplasma genitalium ADN' },
    aliases: ['mycoplasma genitalium', 'mg dna', 'mycoplasma genitalium dna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'UU_DNA',
    loinc: null,
    canonicalName: { en: 'Ureaplasma urealyticum DNA', ro: 'Ureaplasma urealyticum ADN' },
    aliases: ['ureaplasma urealyticum', 'uu dna', 'ureaplasma dna'],
    specimen: 'swab',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
  },
  {
    id: 'MTB_PCR',
    loinc: null,
    canonicalName: { en: 'Mycobacterium tuberculosis PCR', ro: 'Mycobacterium tuberculosis PCR' },
    aliases: ['mycobacterium tuberculosis', 'tb pcr', 'mtb pcr', 'tuberculoza pcr', 'tuberculosis pcr'],
    specimen: 'other',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
    interpretationField: 'expected',
  },
  {
    id: 'FVL',
    loinc: null,
    canonicalName: { en: 'Factor V Leiden', ro: 'Factor V Leiden' },
    aliases: ['factor v leiden', 'f5 leiden', 'mutatia factor v leiden'],
    specimen: 'whole_blood',
    valueType: 'categorical',
    categoricalSystem: { system: 'Genotype', values: ['Wild type', 'Heterozygous', 'Homozygous'] },
    interpretationField: 'expected',
  },
  {
    id: 'PT_G20210A',
    loinc: null,
    canonicalName: { en: 'Prothrombin G20210A', ro: 'Protrombina G20210A' },
    aliases: ['factor ii', 'protrombina g20210a', 'prothrombin g20210a', 'mutatia protrombinei'],
    specimen: 'whole_blood',
    valueType: 'categorical',
    categoricalSystem: { system: 'Genotype', values: ['Wild type', 'Heterozygous', 'Homozygous'] },
    interpretationField: 'expected',
  },
  {
    id: 'MTHFR_C677T',
    loinc: null,
    canonicalName: { en: 'MTHFR C677T', ro: 'MTHFR C677T' },
    aliases: ['mthfr c677t', 'mutatia mthfr c677t'],
    specimen: 'whole_blood',
    valueType: 'categorical',
    categoricalSystem: { system: 'Genotype', values: ['Wild type', 'Heterozygous', 'Homozygous'] },
    interpretationField: 'expected',
  },
  {
    id: 'MTHFR_A1298C',
    loinc: null,
    canonicalName: { en: 'MTHFR A1298C', ro: 'MTHFR A1298C' },
    aliases: ['mthfr a1298c', 'mutatia mthfr a1298c'],
    specimen: 'whole_blood',
    valueType: 'categorical',
    categoricalSystem: { system: 'Genotype', values: ['Wild type', 'Heterozygous', 'Homozygous'] },
    interpretationField: 'expected',
  },
  {
    id: 'HLAB27',
    loinc: null,
    canonicalName: { en: 'HLA-B27', ro: 'HLA-B27' },
    aliases: ['hla b27', 'hla-b27'],
    specimen: 'whole_blood',
    valueType: 'qualitative',
    qualitativeValues: ['Positive', 'Negative'],
  },
  {
    id: 'BRCA1',
    loinc: null,
    canonicalName: { en: 'BRCA1', ro: 'BRCA1' },
    aliases: ['brca1', 'brca 1'],
    specimen: 'whole_blood',
    valueType: 'qualitative',
    qualitativeValues: ['Pathogenic variant detected', 'No pathogenic variant detected'],
    interpretationField: 'expected',
  },
  {
    id: 'BRCA2',
    loinc: null,
    canonicalName: { en: 'BRCA2', ro: 'BRCA2' },
    aliases: ['brca2', 'brca 2'],
    specimen: 'whole_blood',
    valueType: 'qualitative',
    qualitativeValues: ['Pathogenic variant detected', 'No pathogenic variant detected'],
    interpretationField: 'expected',
  },
  {
    id: 'JAK2',
    loinc: null,
    canonicalName: { en: 'JAK2 V617F', ro: 'JAK2 V617F' },
    aliases: ['jak2', 'jak2 v617f', 'mutatia jak2'],
    specimen: 'whole_blood',
    valueType: 'qualitative',
    qualitativeValues: ['Detected', 'Not detected'],
    interpretationField: 'expected',
  },
  {
    id: 'BCR_ABL',
    loinc: null,
    canonicalName: { en: 'BCR-ABL', ro: 'BCR-ABL' },
    aliases: ['bcr abl', 'bcr-abl', 'transcript bcr abl'],
    specimen: 'whole_blood',
    valueType: 'quantitative',
    units: { preferred: '%IS' },
    trendIsClinicallyPrimary: true,
    interpretationField: 'expected',
  },
  {
    id: 'EGFR_MUT',
    loinc: null,
    canonicalName: { en: 'EGFR Mutation', ro: 'Mutatie EGFR' },
    aliases: ['egfr mutatie', 'egfr mutation'],
    specimen: 'tissue',
    valueType: 'narrative',
    interpretationField: 'expected',
  },
  {
    id: 'KRAS_MUT',
    loinc: null,
    canonicalName: { en: 'KRAS Mutation', ro: 'Mutatie KRAS' },
    aliases: ['kras mutatie', 'kras mutation'],
    specimen: 'tissue',
    valueType: 'narrative',
    interpretationField: 'expected',
  },
  {
    id: 'NRAS_MUT',
    loinc: null,
    canonicalName: { en: 'NRAS Mutation', ro: 'Mutatie NRAS' },
    aliases: ['nras mutatie', 'nras mutation'],
    specimen: 'tissue',
    valueType: 'narrative',
    interpretationField: 'expected',
  },
  {
    id: 'BRAF_MUT',
    loinc: null,
    canonicalName: { en: 'BRAF Mutation', ro: 'Mutatie BRAF' },
    aliases: ['braf mutatie', 'braf mutation', 'braf v600e'],
    specimen: 'tissue',
    valueType: 'narrative',
    interpretationField: 'expected',
  },

  // =========================================================
  // MICROBIOLOGIE
  // =========================================================
  {
    id: 'HEMOCULT',
    loinc: null,
    canonicalName: { en: 'Blood Culture', ro: 'Hemocultura' },
    aliases: ['hemocultura', 'blood culture', 'blood cultures'],
    specimen: 'whole_blood',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'THROAT_CULT',
    loinc: null,
    canonicalName: { en: 'Throat Culture', ro: 'Exsudat Faringian' },
    aliases: ['exsudat faringian', 'throat culture', 'pharyngeal culture'],
    specimen: 'swab',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'NASAL_CULT',
    loinc: null,
    canonicalName: { en: 'Nasal Culture', ro: 'Exsudat Nazal' },
    aliases: ['exsudat nazal', 'nasal culture'],
    specimen: 'swab',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'WOUND_CULT',
    loinc: null,
    canonicalName: { en: 'Wound Culture', ro: 'Cultura Secretie Plaga' },
    aliases: ['cultura secretie plaga', 'wound culture', 'plaga cultura'],
    specimen: 'swab',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'SPUTUM_CULT',
    loinc: null,
    canonicalName: { en: 'Sputum Culture', ro: 'Cultura Sputa' },
    aliases: ['cultura sputa', 'sputum culture', 'sputa'],
    specimen: 'other',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'STOOL_CULT',
    loinc: null,
    canonicalName: { en: 'Stool Culture', ro: 'Coprocultura' },
    aliases: ['coprocultura', 'stool culture', 'fecal culture'],
    specimen: 'stool',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'ANTIBIOGRAM',
    loinc: null,
    canonicalName: { en: 'Antibiogram', ro: 'Antibiograma' },
    aliases: ['antibiograma', 'antibiogram', 'susceptibilitate antibiotice', 'antimicrobial susceptibility'],
    specimen: 'other',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },
  {
    id: 'CDIFF',
    loinc: null,
    canonicalName: { en: 'Clostridioides difficile toxin', ro: 'Toxina Clostridioides difficile' },
    aliases: ['clostridium difficile', 'clostridioides difficile', 'toxina a b', 'c difficile toxin'],
    specimen: 'stool',
    valueType: 'qualitative',
    qualitativeValues: ['Positive', 'Negative'],
    interpretationField: 'optional',
  },
  {
    id: 'HPYLORI_AG',
    loinc: null,
    canonicalName: { en: 'Helicobacter pylori Antigen', ro: 'Antigen Helicobacter pylori' },
    aliases: ['helicobacter pylori antigen', 'h pylori antigen', 'antigen helicobacter'],
    specimen: 'stool',
    valueType: 'qualitative',
    qualitativeValues: ['Positive', 'Negative'],
  },
  {
    id: 'CANDIDA_CULT',
    loinc: null,
    canonicalName: { en: 'Candida Culture', ro: 'Cultura Candida' },
    aliases: ['candida', 'cultura candida', 'candida culture'],
    specimen: 'swab',
    valueType: 'microbiology',
    interpretationField: 'expected',
  },

  // =========================================================
  // PAP SMEAR / CYTOLOGY
  // =========================================================
  {
    id: 'PAP',
    loinc: null,
    canonicalName: { en: 'Pap Smear', ro: 'Frotiu Babes-Papanicolaou' },
    aliases: ['pap smear', 'papanicolaou', 'babes papanicolaou', 'citologie cervico-vaginala', 'cervical cytology'],
    specimen: 'swab',
    valueType: 'categorical',
    categoricalSystem: {
      system: 'Bethesda',
      version: '2014',
      values: [
        'NILM',
        'ASC-US',
        'ASC-H',
        'LSIL',
        'HSIL',
        'AGC',
        'Carcinoma',
        'Unsatisfactory',
      ],
    },
    interpretationField: 'expected',
  },

  // =========================================================
  // AMBIGUOUS / NEEDS REVIEW
  // =========================================================
  {
    id: 'AMY_2X',
    loinc: null,
    canonicalName: { en: 'Amylase (duplicate)', ro: 'Amilaza (duplicat)' },
    aliases: [],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'U/L' },
    needsReview: true,
  },
  {
    id: 'CREAT_X',
    loinc: null,
    canonicalName: { en: 'Creatinine (ambiguous specimen)', ro: 'Creatinina (specimen ambiguu)' },
    aliases: [],
    specimen: 'other',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    needsReview: true,
  },
  {
    id: 'LDL_CX',
    loinc: null,
    canonicalName: { en: 'LDL Cholesterol (calculated)', ro: 'Colesterol LDL (calculat)' },
    aliases: ['ldl calculat', 'ldl calculated', 'ldl-c calc'],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    needsReview: true,
  },
  {
    id: 'PHOS_X',
    loinc: null,
    canonicalName: { en: 'Inorganic Phosphate (ambiguous)', ro: 'Fosfat Anorganic (ambiguu)' },
    aliases: ['fosfat anorganic', 'inorganic phosphate', 'ip'],
    specimen: 'other',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    needsReview: true,
  },
  {
    id: 'TBIL_2X',
    loinc: null,
    canonicalName: { en: 'Total Bilirubin (duplicate)', ro: 'Bilirubina Totala (duplicat)' },
    aliases: [],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    needsReview: true,
  },
  {
    id: 'TG_2X',
    loinc: null,
    canonicalName: { en: 'Triglycerides (duplicate)', ro: 'Trigliceride (duplicat)' },
    aliases: [],
    specimen: 'serum',
    valueType: 'quantitative',
    units: { preferred: 'mg/dL' },
    needsReview: true,
  },
];

export const CATALOG_BY_ID = Object.fromEntries(
  ANALYTE_CATALOG.map((entry) => [entry.id, entry]),
) as Record<string, AnalyteEntry>;
